### ISSUE TITLE
Another way to avoid having to write @somepage = SomePageObject.new all over the place

### ISSUE THREAD

**Issue by JohnSmall** [natritmeyer/site_prism#100]
I see at the end of the document you suggest a way to avoid having to instantiate page objects all over the place in your step defs. Here's what I do in Cucumber;-

    module SomePageObjectWrapper

       def some_page
          @some_page ||= SomePageObjectWrapper::Page.new
       end
       class Page < SitePrism::Page
        etc
       end
    end
    # include our module in Cucumber World
    World SomePageObjectWrapper

This adds the method 'some_page' to the Cucumber World object and it's then available in all your steps like so;-

    Then(/^ I do something to some page$/) do
          some_page.do_something
    end

**Comment by vmpj** [comment]
[page-object](https://github.com/cheezy/page-object/wiki/Creating-and-using-page-objects) is using something they call PageFactories which seems interesting:
Basically you define two methods:

    def visit(page_class, params={:using_params => {}}, &block)
    def on(page_class, params={:using_params => {}}, visit=false, &block)

If you wish to perform some activity on that page when you navigate to it you can pass a block to the method.

    When /^I register on the registration page$/ do
      visit RegistrationPage do |page|
        page.register_user
        page.do_something_else
      end
    end

If you are already on a page and wish to interact with it you can use the on_page method.

    Then /^I should be able to cancel my order$/ do
      on CheckoutPage do |page|
        page.cancel_order
        page.do_something_else
      end
    end

**Comment by natritmeyer** [comment]
@JohnSmall @vmpj Thanks for the info :)
