### ISSUE TITLE
Selector-definition-API fragility

### ISSUE THREAD

**Issue by kliuless** [natritmeyer/site_prism#104]
When defining an element (for example), if you misspell the selector type, the default will be used.

Example:
```ruby
# oops, :css will be used here
element :first_name, :xpathh, "//div[@id='signup']//input[@name='first-name']"
```

I think the 2nd arg needs to be checked so only `:css` or `:xpath` is allowed.

Edit: after grepping the site_prism code, I'm guessing you're passing this arg directly to Capybara. Should I open a bug there instead?

**Comment by abotalov** [comment]
> Should I open a bug there instead?

Probably, yes. I think we will output a warning in this case (we can't raise an error because of backwards compatibility).

**Comment by tmertens** [comment]
Yes this is outside the responsibility of site prism IMO. If capybara adds a new selector in the future then site prism will have to add support because the underlying API has changed, even though nothing has actually changed in site prism itself

**Comment by natritmeyer** [comment]
@tmertens is right. Closing.
