### ISSUE TITLE
Inability to use #has_no_element? because it looks at the whole page

### ISSUE THREAD

**Issue by ledestin** [natritmeyer/site_prism#106]
Consider the following code:

``` ruby
it 'is not shown for not-done tasks' do
  expect(task.done.checked?).to eq false
  expect(task.root_element.has_no_css? '.recurrent').to eq true
end
```

Because `#has_no_element?` works on the whole page, I can't use it to write `#has_no_recurrent?` here. And there's also duplication, as I have to write `.recurrent` both in SitePrism page definition and here.

It would be nice if `#has_no_element` only worked within the element, not on the whole page.

**Comment by natritmeyer** [comment]
`#has_no_<element>?` should be working against the section as well as the page, so you should be able to write `#has_no_recurrent?`

After all the siteprism metaprogramming monkey business, the line which will get executed if you call `#has_no<element>?` against a section is the following:

https://github.com/natritmeyer/site_prism/blob/master/lib/site_prism/section.rb#L48-L50

Can you send a pull request with a failing test so I can work out what's going on?

**Comment by ledestin** [comment]
I noticed that you have Capybara.app set, and I suppose that whatever it produces, should be available via `page.body`, but `page.body` is empty.

I'm asking because I need to put some HTML that I can access via css, because to address section.element, I first need to find section on the page.
