### ISSUE TITLE
Reading Nested Section as an Element

### ISSUE THREAD

**Issue by mdorf85** [natritmeyer/site_prism#112]
SitePrism is reading my nested section as an element and not a section.

The code:
![image](https://cloud.githubusercontent.com/assets/7793502/7619677/5fa74320-f988-11e4-8f74-f6ee7d46bba8.png)

The error:
![image](https://cloud.githubusercontent.com/assets/7793502/7619720/92eb4d08-f988-11e4-8313-fa67c28a174c.png)

Because of this I am not able to access the element within the faulty section (:hamburger).

Please advise whether my syntax is off or I've stumbled upon some bug.

Thank you!

**Comment by Vygo** [comment]
I am seeing similar things happening, any update on this one?

**Comment by brbrr** [comment]
This issue could be related to page-object gem itself: https://github.com/cheezy/page-object/issues/292

**Comment by natritmeyer** [comment]
@mdorf85 / @Vygo Are you able to send a pull request with a failing test so I can see what's going on? Screenshots of code aren't the most helpful thing :P

**Comment by natritmeyer** [comment]
I've added a test for deeply nested `sections` (609e981d5feb6255dbd97ef560c18f1f9df9dcb7) but it's passing. I'm struggling to recreate the problem in the siteprism tests.

If you can put together some html in this file: https://github.com/natritmeyer/site_prism/blob/master/test_site/html/section_experiments.htm

...and a failing test in these files:

https://github.com/natritmeyer/site_prism/blob/master/test_site/pages/section_experiments.rb
https://github.com/natritmeyer/site_prism/blob/master/features/page_sections.feature
https://github.com/natritmeyer/site_prism/blob/master/features/step_definitions/page_section_steps.rb

...that would be great.

If there's a bug I'd really like to get rid of it :)

**Comment by luke-hill** [comment]
Hi there. I'm going to be looking into the entire history list of issues e.t.c. and this one appears to be stale. Could you give a brief update as to what you plan to do with this.

If you plan to land a PR soon or already have done. Can you close this issue
If you think it's no longer relevant. Can you close this issue.

If possibly can you provide some update in the next couple of weeks (I'm aware this issue is several years old)
