### ISSUE TITLE
Ability to pass custom processor in url

### ISSUE THREAD

**Issue by PushkarPahare** [natritmeyer/site_prism#113]
I have a use case where I want to run a test simultaneously on test and prod in two different sessions and compare the UI elements. I have implemented the hack in my page object, to call set_url from initialize based on the request

    def initialize(port_type => :test)
       if port_type === :test
           MyPage.set_url("ENV['prod']/xyz/abc")
       else
          MyPage.set_url("ENV['test']/xyz/abc")
        end
    end

but the problem is i have to handle this in call pages. What I would like to have is to able to pass a processor which can take care of this.

    class ProdProcessor
       def self.transform(name, value)
          return value.gsub(/.* /, "ENV['prod']") if name == "port"
          return value
       end
    end
 
    class TestProcessor
       def self.transform(name, value)
          return value.gsub(/.*/, "ENV['testport']") if name == "port"
          return value
       end  
    end

and during page object loading, I can pass the preprocessor, without modifying the page objects as such.

But Page::url does not accept processors : 

    def url(expansion = {})
      return nil if self.class.url.nil?
      Addressable::Template.new(self.class.url).expand(expansion).to_s
    end

**Comment by natritmeyer** [comment]
This isn't something I'm looking to support in siteprism. There are better ways of managing environments, e.g. reading in the target env from a config file at the start of a test run.
