### ISSUE TITLE
Seeing 'Stack Level too deep' errors when switching from 2.6 to 2.7

### ISSUE THREAD

**Issue by devanoff11** [natritmeyer/site_prism#115]
This works: 
profile_page.alerts_table.alerts_rows.first

This seg faults with stack level too deep in 2.7:
profile_page.alerts_table.alerts_rows.first.resolve_link

That line works just fine in 2.6

**Comment by natritmeyer** [comment]
Code examples? Stack traces? Anything?

**Comment by devanoff11** [comment]
Failure/Error: profile_page.current_alerts.alerts(text: 'Complaint').first.resolve
     SystemStackError:
       stack level too deep
     # /Users/devanoff/.rvm/gems/ruby-2.2.2/gems/site_prism-2.7/lib/site_prism/element_container.rb:8:in `block (2 levels) in element'

< same line above/below shows up about 1000 times >

     # /Users/devanoff/.rvm/gems/ruby-2.2.2/gems/site_prism-2.7/lib/site_prism/element_container.rb:8:in `block (2 levels) in element'
     # ./spec/support/page_objects/pages/account_profile_page.rb:35:in `resolve'
     # ./spec/features/profile_alerts_spec.rb:35:in `block (3 levels) in <top (required)>'

**Comment by devanoff11** [comment]
This is what I was selecting:
![screen shot 2015-07-07 at 8 42 52 am](https://cloud.githubusercontent.com/assets/11722223/8547430/6bce2e94-2484-11e5-9d37-39568e0bd2db.png)

and in my page file:
  section :current_alerts, '.current-alerts' do
    sections :alerts, 'tbody tr' do
      element :action_link,  'td:nth-child(5) a'
      def resolve
        action_link.click
      end 
    end 
  end

**Comment by ineverov** [comment]
Issue was resolved. It was element definition problem
There was element defined with name :class. So it was looping on line 
https://github.com/natritmeyer/site_prism/blob/master/lib/site_prism/element_container.rb#L8 

To prevent such problems in future, maybe we should add check for method name?
