### ISSUE TITLE
Wait for elements to not exist (Selenium::WebDriver::Error::StaleElementReferenceError: stale element reference: element is not attached to the page document)

### ISSUE THREAD

**Issue by xam7247** [natritmeyer/site_prism#122]
Hi,

I have a collection of elements defined as  elements :menu_items, ".class_identifier_for_each_elem".
Now, I need to assert something after all menu items disappear. 

On trying to use page.wait_until_menu_items_invisible, I am getting the following error: 
Selenium::WebDriver::Error::StaleElementReferenceError:
       stale element reference: element is not attached to the page document

I am assuming this is due to the fact that the menu items no more exist on the page, and hence the matcher is falling over trying to check for their visibility. 

While site_prism provides non-existence matchers at a given point, I couldn't find anything to wait for non-existence of element(s). Do we have something in site_prism to do this?

**Comment by tgaff** [comment]
Maybe try the `has_no` methods:
```ruby
expect(@page).to have_no_menu_items
```

**Comment by xam7247** [comment]
Thanks @tgaff. Actually I need this within my page object, hence don't want to assert.
Actually wait_until_menu_items_invisible works, but if I move the browser window, it fails with the said error. Bizarre !!

**Comment by xam7247** [comment]
Thanks tgaff. I need this within my page object, hence don't want to put an assert.
Interestingly, if I register a single :menu_item with it's css class and use "wait_until_menu_item_invisible", I am able to work through it. But, if I try to wait for all such elements defined as sections, it fails with the said error.

**Comment by xam7247** [comment]
Any updates on this, please. This is further blocking me for sections too. 
I have sections defined for a repeating section. Ex: 
  sections :test_sections, SectionItem, <some selector>

Now I want to wait for a particular section to be present (not all/any section)
wait_for_test_sections[5] # not supported. 
wait_for_test_sections (will be true if even a single section exists)

**Comment by tmertens** [comment]
@xam7247 Is the element you're checking for nested inside a section that is also removed from the DOM?  I've seen issues with Capybara not handling nested element queries well when an ancestral element is removed or updated in the DOM.

**Comment by tmertens** [comment]
Regarding your other question, you can use Capybara's Query parameters to accomplish what you are trying to do.  See https://github.com/natritmeyer/site_prism#using-capybara-query-options

**Comment by ditchfieldcaleb** [comment]
Still having this issue.

**Comment by luke-hill** [comment]
Hi there. I'm going to be looking into the entire history list of issues e.t.c. and this one appears to be stale. Could you give a brief update as to what you plan to do with this.

If you plan to land a PR soon or already have done. Can you close this issue
If you think it's no longer relevant. Can you close this issue.

If possibly can you provide some update in the next couple of weeks (I'm aware this issue is several years old)

**Comment by matisnape** [comment]
I'm experiencing this in an assertion:

`expect(q_form.questions_list).to have_content multiple_choice_question[:text]`

```
def questions_list
    added_questions.map { |item| item.title.text }
  end
```

```
  sections :added_questions, :xpath, "//rt-open-questions-item" do
    element :title, :xpath, ".//div[@class='item-title']"
    element :options, "rt-open-questions-item div.child-items"
    element :edit_btn, :xpath, ".//*[*[rt-icon[@name='edit']]]"
    element :delete_btn, :xpath, ".//*[*[rt-icon[@name='delete']]]"
  end
```

error:
```
Selenium::WebDriver::Error::StaleElementReferenceError:
       stale element reference: element is not attached to the page document
         (Session info: chrome=66.0.3359.181)
         (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.4 x86_64)
```

**Comment by luke-hill** [comment]
This is a separate issue and ideally if you're having problems you should re-open one.

You are asserting an array of strins against an object, which will fail as it doesn't make sense.

Try using all matchers, or an inclusion matcher
