### ISSUE TITLE
Unable to find hidden elements via site_prism

### ISSUE THREAD

**Issue by si-mikey** [natritmeyer/site_prism#132]
When I add an an element to a page class that is hidden ( hidden input ) when I do @page.element_name  it returns that it can't find the element. I capybara I can pass in :visible false  option and the element is found but how do I pass that into elements on the page class? or is this a bug?

**Comment by twalpole** [comment]
From https://github.com/natritmeyer/site_prism#using-capybara-query-options  - you can pass in capybara options to element methods

    @page.element_name(visible: false)
