### ISSUE TITLE
undefined method `load_validation'

### ISSUE THREAD

**Issue by frankvu** [natritmeyer/site_prism#138]
class FileManagerPage < SitePrism::Page

  #Top Menu
  element :files_tab,                   :link,    'Files'

  #check if page is loaded?
  load_validation { [ has_no_files_tab?, 'Files tab did not appear' ] }

end

Above is my class, when calling @my_app.file_manager_page.loaded? it shows undefined method `load_validation'

**Comment by murphyslaw** [comment]
The feature is not yet released. `site_prism` version `2.8` does not provide this functionality. See the [README.md](https://github.com/natritmeyer/site_prism/tree/v2.8) matching your version of the gem.

**Comment by frankvu** [comment]
Thanks
