### ISSUE TITLE
siteprism with minitest

### ISSUE THREAD

**Issue by leoGalani** [natritmeyer/site_prism#144]
Hi,

Im managing to use siteprism with minitest and capybara so far, but im struggling to use the elements inside my test cases (and i call the page objects methods its all good)

Exemple: 

I have a SitePage.SiteSection.Element to assert on my tests but im getting:

```
Selenium::WebDriver::Error::InvalidSelectorError: The given selector #<Capybara::Node::Element:0x007ff5b4f37b48> is either invalid or does not result in a WebElement. The followin
```

the code is:

```
page.must_have_selector admin.profile.email, text: profile["email"]
```

Any idea how to handle it?

**Comment by seanfcarroll** [comment]
It's a good question. Does it work with Minitest?

**Comment by luke-hill** [comment]
This is an old topic. If you're having an issue which you believe is related to the code-base, please open up a new issue with a reproducible concise example. Ideally in a small git repo.

Siteprism should work with mini-test, although we don't test with it personally.
