### ISSUE TITLE
all_there? should give more explicit failure message

### ISSUE THREAD

**Issue by stevof** [natritmeyer/site_prism#146]
When all_there? fails, the current failure output is not very helpful to figure out what element/section has a problem:

```
Failure/Error: expect(home_page).to be_all_there
       expected `#<CourseHomePage:0x007ff910ec8518 @course_num="MAN 101", @course_title="How to Manny">.all_there?` to return true, got false
```

IOW, all_there? is good at finding problems, but not good at helping you pinpoint how to fix them. For that reason, I don't find all_there? useful at all.

It would be better if the output stated exactly which element could not be found. Ideally, the output would be like Capybara gives when you try to access an element that can't be found:

```
Failure/Error: expect(home_page.page_heading).to have_text('COURSE HOME')
     Capybara::ElementNotFound:
       Unable to find css "h2.page-title > spqn.title-text"
```

So, if all_there? could have failure output something like this, I'd love it:

```
Failure/Error: expect(home_page).to be_all_there
       expected `#<CourseHomePage:0x007ff910ec8518 @course_num="MAN 101", @course_title="How to Manny">.all_there?` to return true, got false 
       (element 'page_heading' not found: Unable to find css "h2.page-title > spqn.title-text")
```

**Comment by tmertens** [comment]
@stevof See also https://github.com/natritmeyer/site_prism#load-validations

**Comment by stevof** [comment]
@tmertens Load Validations -- very cool, is that new? I'll check it out. But I don't think that's what I'm asking for. The thing that prompted me to open this ticket about all_there? is this: our designers are refreshing the UI and making changes to markup and CSS. I want to call all_there? and have it tell me which elements can't be found. 

I realize I could write code to do this, either roll my own, or use Load Validations, but that's a ton of work. Seems like all_there? is already iterating through the elements, so i just want it to have a more helpful error message.

**Comment by luke-hill** [comment]
booleans favour true / false assertions. Load Validations are being enhanced slightly at the moment
