### ISSUE TITLE
wait_for_<element_name> doesn't have timed wait loop

### ISSUE THREAD

**Issue by skanchana** [natritmeyer/site_prism#149]
Hello Everyone,
Method defined by siteprism for wait_for_<element_name> keyword not waiting for the default wait time and returns from element_exists?.  Test scenarios randomly failing because of no timed wait.  Modified the code with timed wait loop and submitting PR.  Please let me know if there is different way to make this method wait for the element by default.

Regards,
Kanchana

**Comment by tmertens** [comment]
Can you provide an example of your usage where you are seeing problems with this method?  It definitely waits the default wait time if implicit waits are enabled.

**Comment by skanchana** [comment]
Thanks for the response Tim.  We are using css structure to access the UI (implemented using Angular JS) in the webpage.  

The test scenarios are failing randomly with error message like below,

Unable to find css "div:nth-child(3) > span > div > button:nth-child(3)
Unable to find css "#sidebar > aside"

undefined method `summary' for nil:NilClass  --> It fails after the wait_for method being called for the collection like below,

class Note < SitePrism::Section
  element :task, "td:nth-child(1) > input"
  element :summary, "td:nth-child(3) > div.note-summary"
  element :body, "td:nth-child(3) > div.ng-binding"
end

class Interactions < SitePrism::Section
  sections :notes, Note, "#notes-list > table > tbody > tr"
  section :filters, Filters, "div.note-list-filters"
end

wait_for_<element> called as below
page.interactions.wait_for_notes

Could you please provide your feedback on the way we are accessing this method?

**Comment by tmertens** [comment]
@skanchana Do you have implicit waits enabled for SitePrism? See https://github.com/natritmeyer/site_prism#using-capybara-implicit-waits

**Comment by skanchana** [comment]
Yes Tim, we enabled implicit waits for siteprism in our spec_helper.rb as below,

SitePrism.configure do |config|
  config.use_implicit_waits = true
  config.include Capybara::Angular::DSL 
end

**Comment by joaquinstan** [comment]
Same happening here, I've noticed it happens when trying to wait for `sections`. What is the default behaviour for waiting for `sections`?

**Comment by O-kasso** [comment]
Has anyone had any luck with this?

I'm experiencing this issue as well. I have `SitePrism.use_implicit_waits = true` set in my `spec_helper`, however for some elements, no wait occurs. I get this error immediately after attempting to find the element defined in my page object with the `element` keyword:
```
Capybara::ElementNotFound Exception: Unable to find xpath "//button[contains(@class, 'layerConfirm')]"
```

**Comment by luke-hill** [comment]
Implicit waits should be used with an air of caution. Explicitly waiting for an element is often a more measured approach. If you're struggling to find an element that's not really a concern of Siteprism.

If this issue persists and there is a genuine issue with siteprism please feel free to reopen a more up to date issue
