### ISSUE TITLE
"native" accessor method for sections

### ISSUE THREAD

**Issue by tommyh** [natritmeyer/site_prism#155]
Hi,

I'm working on a new project using site_prism and I'm pretty pumped about it.  So first off, thanks!  :)

Feature request: I'm using applitools eyes to take screenshots of regions of the page.  To take a screenshot of a region, I need to give the applitools gem a native selenium element.  It would be helpful if sections had a helper method to make this easier.

Image this page model:

``` ruby
class Home < SitePrism::Page
  element :search_field, "input[name='q']"
  section :menu, MenuSection, "#gbx3"
end
```

For a site_prism `element`, the capybara `native` method is already there, so my code is very clean:

``` ruby
eyes.check_region(:element, @home.search_field.native, "my search field")
```

For a site_prism `section`, the capybara `native` method isn't there, so I always have to go through the `root_element`, which is a bit awkward:

``` ruby
eyes.check_region(:element, @home.menu.root_element.native, "my menu")
```

What I'd like todo, if you are cool with it, is an open a pull request to add this helper:

```
class SitePrism::Section
  def native
    root_element.native
  end
end
```

So that my code could look like this:

``` ruby
eyes.check_region(:element, @home.menu.native, "my menu")
```

Does this sound like a good change?  It's working in my project but are there stumbling blocks you can think of which I'm not aware of?

Thanks,
Tom

**Comment by Carlbc18** [comment]
I think this is a useful idea Tom. (Upvote)

**Comment by tommyh** [comment]
@Carlbc18 - thanks!  :)

@natritmeyer - any thoughts on this?  Good idea?  Terrible idea?  If you like it, I'll open up a pull request with tests.

**Comment by natritmeyer** [comment]
Great idea :)

**Comment by luke-hill** [comment]
Hi there. You've raised a good point, and in short we're curious to know where you got to with t.

If you're happy landing the PR yourself, then feel free to do so. Ideally you need to make sure that you include some Documentation and a snippet or SSCCE to test against so we can see your code in action.

Even better would be 2 SSCCE's. One where it fails and one where it works (But this isn't 100% necessary)

Can you give us an update when you're available to, as to where you're at with this.

**Comment by luke-hill** [comment]
Closing in favour of https://github.com/natritmeyer/site_prism/pull/223
