### ISSUE TITLE
New release eta?

### ISSUE THREAD

**Issue by dbrans** [natritmeyer/site_prism#156]
Hi,
Are there any plans to drop a new site_prism release soon?
Cheers,
Derek

**Comment by natritmeyer** [comment]
There are. Very shortly :)

**Comment by joviano-dias-springernature** [comment]
No 2.9 Release notes https://github.com/natritmeyer/site_prism/blob/master/HISTORY ?

**Comment by luke-hill** [comment]
Similar issues. WIll be looked at soon going forward.

V2.9.1 of the gem cut will be available before March
