### ISSUE TITLE
Routes?

### ISSUE THREAD

**Issue by tucknats** [natritmeyer/site_prism#159]
cheezy's PageObject implementation (https://github.com/cheezy/page-object) has a 'routes' feature that lets you define navigational flows to particular pages. Something like this,

PageObject::PageFactory.routes = {
    :default => [[HomePage, :select_puppy],
                 [DetailsPage, :add_to_cart],
                 [ShoppingCartPage, :proceed_to_checkout],
                 [CheckoutPage, :checkout]]
}

And then, in a step definition, you just call 

  navigate_to(CheckoutPage)

Which avoids repeating all the steps to get to that page. Is there something similar available for SitePrism?

**Comment by natritmeyer** [comment]
>Is there something similar available for SitePrism?

No. Nice feature, but nothing that couldn't be achieved in a simple method.
