### ISSUE TITLE
RSpec::Matchers doesnt works in Page classes siteprism

### ISSUE THREAD

**Issue by jtlimo** [natritmeyer/site_prism#165]
When I try to use this code: `expect(element.text).not_to be_nil`

`NoMethodError: undefined method expect' for #<Class:0x007fce17aba508> Did you mean?  exec`

This is my gemlist

**\* LOCAL GEMS ***

activesupport (5.0.0)
addressable (2.4.0)
bigdecimal (1.2.8)
builder (3.2.2)
bundler (1.12.5)
bundler-unload (1.0.2)
byebug (9.0.5)
capybara (2.7.1)
capybara-select2 (1.0.1)
childprocess (0.5.9)
coderay (1.1.1)
concurrent-ruby (1.0.2)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
debase (0.1.4)
debase-ruby_core_source (0.9.1)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
domain_name (0.5.20160615)
executable-hooks (1.3.2)
factory_girl (4.7.0)
ffi (1.9.14, 1.9.11, 1.9.10)
gem-wrappers (1.2.7)
gherkin (4.0.0)
http-cookie (1.0.2)
i18n (0.7.0)
io-console (0.4.5)
json (2.0.2, 2.0.1, 1.8.3)
method_source (0.8.2)
mime-types (3.1, 2.99.2)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.9.0, 5.8.3)
multi_json (1.12.1)
multi_test (0.1.2)
net-telnet (0.1.1)
netrc (0.11.0)
nokogiri (1.6.8)
pkg-config (1.1.7)
power_assert (0.2.6)
pry (0.10.4)
pry-byebug (3.4.0)
psych (2.0.17)
rack (2.0.1, 1.6.4)
rack-test (0.6.3)
rake (10.4.2)
rdoc (4.2.1)
rest-client (2.0.0, 1.8.0)
rspec (3.5.0, 3.4.0)
rspec-core (3.5.2, 3.4.4)
rspec-expectations (3.5.0, 3.4.0)
rspec-mocks (3.5.0, 3.4.1)
rspec-support (3.5.0, 3.4.1)
ruby-debug-ide (0.4.32)
rubygems-bundler (1.4.4)
rubyzip (1.2.0)
rvm (1.11.3.9)
selenium-webdriver (2.53.4, 2.53.3)
site_prism (2.9)
slop (3.6.0)
test-unit (3.1.5)
thread_safe (0.3.5)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.7.2)
websocket (1.2.3)
xpath (2.0.0)

Someone help me with this issue?

Tks;

**Comment by natritmeyer** [comment]
Could do with some more info
