### ISSUE TITLE
When does the profit begin?

### ISSUE THREAD

**Issue by molfar** [natritmeyer/site_prism#167]
I recently became acquainted with all this page objects and siteprism in particular. Before I used only feature specs with capybara. I read all docs and examples, and for now cant understand the purposes of using page objects. My specs code not going to become shorter... What is the main advantages of all of this? For example

```
expect(page).to have_selector '.navbar' # Capybara
expect(homepage).to have_navbar # Siteprism

expect(page).to have_selector 'h1', text: 'Cool page' # Capybara
expect(homepage).to have_heading text: 'Cool page' # Siteprism

fill_in '#name', with: 'Taras' # Capybara
login_form.name.set 'Taras' # Siteprism
```

The only thing of this approach is that all css selectors collected in single place? And are more maintainable? And thats all?

I thought that page object can have some expectations? For example to check if page contain all needed attributes of some object

```
just_created_post = Post.create title: 'Some cool title'
expect(homepage.posts).to have_post just_created_post
```

For now I see the main purposes of these page objects to wrap css selectors to nicely named methods. Could you explain how to use site prism for more complex examples, than in readme file?

**Comment by natritmeyer** [comment]
http://martinfowler.com/bliki/PageObject.html
