### ISSUE TITLE
Does expect(my_page_object).to have_blah actually wait?

### ISSUE THREAD

**Issue by oscarkwan** [natritmeyer/site_prism#171]
In my test case

using `expect(my_page_object).to have_blah` doesn't actually wait for the element. 

Whereas using `have_css` will.

**Comment by tmertens** [comment]
@oscarkwan Please provide more context.  `has_<element>?` will wait for the element for the default Capybara timeout, or the wait time you have specified for the element in your page object.

**Comment by tmertens** [comment]
I should add that SitePrism, historically, did not use Capybara's implicit waits, and you must tell it to do so: https://github.com/natritmeyer/site_prism#using-capybara-implicit-waits

**Comment by natritmeyer** [comment]
By design, the `has_element?` method doesn't wait. It's intended to be used to see if an element exists, not wait around for it to exist.
