### ISSUE TITLE
HTMl rendering from some JS action doesn't present in HTML DOM. 

### ISSUE THREAD

**Issue by awais4123** [natritmeyer/site_prism#172]
I am trying to test my html page . I am using datatables and the data/html is coming from some JS request. When i am trying to test that part it doesn't appear in the html dom and i am unable to test it. Can you please suggest any possible solution so that i can test the html part which is coming through JS?

**Comment by tmertens** [comment]
can you give an example of your test code and html dom snippet that you are trying to verify?

**Comment by awais4123** [comment]
My scenario is bit difficult to explain here. I am going to give very simple example .
<html>
  <div class="main_div">
     <div class="inner_div">
        <span>This is test </span>
     </div>
  </div> 
</html>

<javascript>
$('.main_div').html('')
</javascript>



// in page_object i have like this 
  section :text, TextSection, ".main_div .inner_div span"

and in spec text.html contains this html . but with javascript it should not be there . So my point is javascipt is not running at all.

**Comment by tmertens** [comment]
are you sure the driver you are using supports JS?  Have you tried the same assertion using standard capybara methods without the page object and do you get different results?

**Comment by awais4123** [comment]
No i don't think even capybara will do this. I am using selenium and requiring selenium in spec_helper. What else i need to do in order to run javasciprt?

**Comment by tmertens** [comment]
If you are using selenium then you should be able to see in your browser what is happening.  So, run the test, throw in a `binding.pry` (via the `pry` gem) and make sure it behaves/looks as expected.  If it looks OK, then the JS firing is not the issue and it is probably a configuration/assertion issue.

Please post the specific query/assertion in your test.

**Comment by awais4123** [comment]
Ok. i got your point . I have just one question. 
Lets say i am NOT opening browser through selenium and i am testing application with capybara/ page_objects. will simple javascript will execute?

**Comment by tmertens** [comment]
it depends on the driver you are using.  See the capybara documentation for details, not all drivers support JS, and not all drivers support JS equally (the closer you are to ES5/edge JS features, the less likely they will be supported by any given underlying driver/browser).
