### ISSUE TITLE
Timeout value for `.load`

### ISSUE THREAD

**Issue by luke-hill** [natritmeyer/site_prism#173]
Firstly let me just say your documentation is great, and we use this a lot at our Company (OntheBeach). It makes training our testers and automating a lot easier.

I read through the internals of the `.load` function inside `page.rb` and couldn't find anywhere you set a timeout. For IE we (Admittedly only about 1% of the time), get a timeout on the `.load` function. It seems as if the actual value for the timeouts based off our grid errors is about 16milliseconds. For IE we would want to increase this.

Thoughts?

**Comment by tmertens** [comment]
@luke-hill cc/ @natritmeyer #134 enables page-specific wait times, which allows you to set wait times on a page-by-page basis (but not browser-specific).  That PR is still waiting on feedback though.

What do you mean about the value for timeouts being 16ms?  The load action is timing out in this period?  That would indicate your default wait time is set extremely low, is it not?

If you want it to be browser specific, you could also just set the default wait time to a different value in your Capybara configuration when using IE

**Comment by luke-hill** [comment]
We never set the value to 16ms, I'm not 100% certain that it is timing out in this time. Here is a full copy of the error we get (It is rescued and then raised again so we can capture a screenshot)

```
Failed to navigate to https://www.ebeach.no/?otb_variant=AA. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 16 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'node138107', ip: '172.23.4.148', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:33668/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 61b8ec5a-8715-4b79-b68e-789f50fc8a1b (org.openqa.selenium.WebDriverException) (Selenium::WebDriver::Error::UnknownError)
```

**Comment by tmertens** [comment]
That is a selenium-webdriver error.  16ms is the command duration, it is not a Capybara timeout error.  You should search for similar errors, this is not a capybara/site_prism issue.
