### ISSUE TITLE
Using capybara `with: value` to wait for values

### ISSUE THREAD

**Issue by AndrewVos** [natritmeyer/site_prism#176]
I'm not sure this is even possible in Capybara, but I have a situation where my tests are asserting on a value of a text field, and I can't for the life of me find out how to do it with site_prism.

Is there something entirely obvious I'm missing?

I'm kind of tempted to write a `has_value?` so I can do something like this:

```ruby
expect(@page.element).to have_value("Hello")
```

This sort of approach will not work under JS tests:

```ruby
expect(@page.element.value).to eq 'Hello'
```

**Comment by twalpole** [comment]
When defining your element, if you define it as a :field selector you can then pass the `with` option to it when attempting to find it.

    element :my_text_field, :field, 'field id/name/label text'

    expect(@page.element(with: 'expected value')).to be

**Comment by AndrewVos** [comment]
Using this as a workaround:

```
module Capybara
  module Node
    class Element
      def has_value?(v, options = {})
        wait = options
               .fetch(:wait, Capybara.default_max_wait_time)
               .seconds

        start = Time.zone.now

        loop do
          return true if value == v
          break if Time.zone.now - start > wait
        end

        raise Capybara::ExpectationNotMet, "expected to find value \"#{v}\" in \"#{value}\""
      end
    end
  end
end
```
