### ISSUE TITLE
SitePrism doesn't obey namespacing

### ISSUE THREAD

**Issue by luke-hill** [natritmeyer/site_prism#180]
We have the following structure
```
support-|
              |stage2-|
                           |bags.rb
              |stage4-|
                           |bags.rb
```
When I access @app.stage2.bags.METHOD it should be the method on stage2 bags
When I access @app.stage4.bags.METHOD it should be the method on stage4 bags.

It always accesses the stage4 method if they exist on both files (Which some methods do). This is a bug as it should only access the stage2 method when I access it that way, and the stage4 method when I access it the other way

**Comment by tmertens** [comment]
Can you provide more information?  If you can show the `bags.rb` implementations and test code that you are having issues with it would be helpful.

**Comment by luke-hill** [comment]
Oki, thought I'd given enough. Mybad.

Step definition code looks like the above

```
 @app.stage2.bags.add_bags(bags,limit)
```

And later on in a MUCH different step definition we have

```
 @app.stage4.bags.add_bags(bags,limit)
```

However both are calling the stage4 method.

`stage2.rb`
```
class Stage2 < SitePrism::Page

  def initialize
    check_login_status
  end

  sections(:flight_search_results, Results, '.flight-result__outline')
  section(:filter_section, Filters, '[data-tab-id="filters"]')
  section(:bags, Bags, '.baggage-selector__bags')
  section(:graph, Graph, '.flight-price-graph')
...
```

`stage4.rb`
```
class Stage4 < SitePrism::Page

  def initialize
    wait_for(timeout: 10) { page.has_css?('.sidebar-basket') }
    check_login_status
  end

  section(:bags, Bags, '.baggage-ancillary')
  section(:transfers, Transfers, '[data-ancillary="transfers"]')
  section(:insurance, Insurance, '[data-ancillary="insurance"]')
  section(:parking, Parking, '[data-ancillary="carparks"]')
...
```

`bags.rb in stage2.rb`

```
class Bags < SitePrism::Section

  element(:remove_bags_button, '.baggage-controls__button[data-direction="-1"]')
  element(:bags_quantity, '.baggage-controls__quantity')
  element(:add_bags_button, '.baggage-controls__button[data-direction="1"]')

  def add_bags(number_of_bags, bag_limit)
    if number_of_bags > bag_limit
      $LOG.warn('Attempting to add too many bags. No bags will be added')
    else
      number_of_bags.times do |bag_index|
        add_bags_button.click
        wait_for_results_reload
        wait_for(timeout: 5, message: timeout_message) { number_of_bags_included == (bag_index + 1) }
      end
    end
    number_of_bags_included
  end

...
```
`bags.rb in stage4.rb`

```
class Bags < SitePrism::Section

  element(:add_bags_button, '.baggage-controls__button[data-direction="1"]')
  element(:number_of_bags_label, '.baggage-controls__quantity')
  element(:total_bag_price, '.ancillary__price.ancillary-option__bag-price')
  element(:remove_bag_button, '.baggage-controls__button[data-direction="-1"]')

  def add_bags(number_of_bags, bag_limit)
    if number_of_bags > bag_limit
      number_of_bags = 0
      $LOG.warn('Attempting to add too many bags. No bags will be added')
    else
      wait_for(message: 'Could not find bag button') { has_add_bags_button? }
      number_of_bags.times { add_bags_button.click }
    end
    number_of_bags
  end
...
```

**Comment by luke-hill** [comment]
![image](https://cloud.githubusercontent.com/assets/20105237/24852534/c4b692f8-1dcf-11e7-9627-1f552bfd1633.png)
Issue I'm seeing

**Comment by tmertens** [comment]
You need to namespace or use unique names for your Bags classes.  The two have the same name, so whichever one is loaded second will override the method definition in the first.

**Comment by luke-hill** [comment]
They are namespaced. That's my point. Once is in the directory `features/support/stage2/bags.rb`. So a *unique* call "should" be @app.stage2.bags.METHOD

The other one is in `features/support/stage4/bags.rb` So a *unique* call "should" be @app.stage4.bags.METHOD. If they're not, then that's an issue on the SitePrism end. As other namespacing techniques, such as `requires` or loadpaths, all work correctly

**Comment by tmertens** [comment]
What class/module is each `Bags` implementation namespaced under?  The code you pasted above either omits the namespacing, or they are not actually namespaced.  Ruby does not impute the namespacing of classes from the directory structure of source files.  Please paste code to reflect the namespacing of each `Bags` class.

**Comment by luke-hill** [comment]
`stage2/all.rb`

```
require_relative 'filters'
require_relative 'graph'
require_relative 'results'
require_relative 'bags'
require_relative 'stage2'
```

`stage4/all.rb`

```
require_relative 'bags'
require_relative 'basket'
require_relative 'insurance'
require_relative 'parking'
require_relative 'transfers'
require_relative 'stage4'
```

`/all.rb`
```
require 'bundler/setup'
require 'capybara/rspec'
require 'capybara/cucumber'
require 'capybara/poltergeist'
require 'selenium-webdriver'
require 'site_prism'
require 'rspec'

require_relative 'cancellation/all'
require_relative 'cms/all'
require_relative 'cmyb/all'
require_relative 'deal/all'
require_relative 'helpers/all'
require_relative 'stage1/all'
require_relative 'stage2/all'
require_relative 'stage3/all'
require_relative 'stage4/all'
require_relative 'stage5/all'
require_relative 'stage6/all'

include LoginFunctionality
include Methods
include LogInitializer
include Scrapbook
include ErrorChecks
```
Link references for each requirement go to the correct version of the file.

**Comment by tmertens** [comment]
@luke-hill per my previous comment:

> Ruby does not impute the namespacing of classes from the directory structure of source files.

e.g. given you have the files:

`support/stage2/bags.rb`
`support/stage4/bags.rb`

And the header of each file looks like:

```ruby
class Bags < SitePrism::Section
  def add_bags
    # do something...
  end
end
```

**Both** of these files declare the `Bags` class constant in the **global** namespace.  This means you are declaring a single `Bags` class constant.  If `stage2/bags.rb` is required first, followed by `stage4/bags.rb`, then this means that `stage4/bags.rb` will **redefine** the implementation of `add_bags`, as well as any other method definitions that share the same name in both files.

See the rubymonk tutorial on redefining methods: https://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/37-classes-inheritance/lessons/88-redefining-overriding-and-super

In order to namespace your declarations so they do not clobber one another, you must namespace them within a module or class namespace so that each `Bags` implementation is declared within a unique namespace:

`support/stage2/bags.rb`
```ruby
module Stage2
  class Bags < SitePrism::Section
    def add_bags
      # do something...
    end
  end
end
``` 

`support/stage2/page.rb`
```ruby
module Stage2
  class Page < SitePrism::Page
    section(:bags, Stage2::Bags, '.baggage-selector__bags')
  end
end
``` 

Note that the `Stage2` class is now `Stage2::Page`, because we cannot declare a module and a class with the same name.  So, we use `Stage2` as the parent module namespace, and `Page` as the class name.  You can rename these as needed, or even namespace `Bags` under the `Stage2` class (instead of using a module), but that presents other potential problems which I won't get into right now.

`support/stage4/bags.rb`
```ruby
module Stage4
  class Bags < SitePrism::Section
    def add_bags
      # do something else...
    end
  end
end
``` 

`support/stage2/stage4.rb`
```ruby
module Stage4
  class Page < SitePrism::Page
    section(:bags, Stage4::Bags, '.baggage-ancillary')
  end
end
``` 

Now, you can see that each reference to `Bags` is clearly referring to different namespaced implementations, rather than a single implementation in the global namespace.

**Comment by luke-hill** [comment]
Looks like the implementation i've got won't work full stop then. Going to need to seriously re-think how to code this. as in our App class we reference
```
def stage1
  @stage1 ||= Stage1.new
end
```

Going to need to do something like `Stage1::Page.new` I imagine
