### ISSUE TITLE
create_visibility_waiter and similar methods do not combine find_args and runtime_args correctly

### ISSUE THREAD

**Issue by koendehondt** [natritmeyer/site_prism#181]
Context in which I found the issue: site_prism 2.9, capybara 2.10.2.

I like to use this:
```
element  :page_title, ".page_title", text: "My page title"
```
and use the element in a visibility waiter:
```
wait_until_page_title_visible
```

That does not work correctly. Capybara shows a warning:
```
gems/capybara-2.10.2/lib/capybara/queries/selector_query.rb:26:in `initialize' :
Unused parameters passed to Capybara::Queries::SelectorQuery : [{:text=>"My page title"}]
```
site_prism's `create_visibility_waiter` does not combine the `find_args`, the `runtime_args`, and `visible: true` correctly. Here is the method:
```
def create_visibility_waiter(element_name, *find_args)
  method_name = "wait_until_#{element_name}_visible"
  create_helper_method method_name, *find_args do
    define_method method_name do |timeout = Waiter.default_wait_time, *runtime_args|
      Timeout.timeout timeout, SitePrism::TimeOutWaitingForElementVisibility do
        Capybara.using_wait_time 0 do
          sleep 0.05 until element_exists?(*find_args, *runtime_args, visible: true)
        end
      end
    end
  end
end
```
In the given example, `create_visibility_waiter` is called with these `find_args`:
```
[".page_title", {:text=>"My page title"}]
```
When `wait_until_page_title_visible` is called, the `runtime_args` are:
```
[]
```
`wait_until_page_title_visible` calls `element_exists?` with these arguments:
```
[".page_title", {:text=>"My page title"}, {:visible=>true}]
```
`element_exists?` sends the arguments to Capybara's `has_selector?`, but the argument list is not supported.

The `find_args`, the `runtime_args`, and `visible: true` should be combined differently, so that the correct argument list is passed to `element_exists?`. Something like this:
```
def create_visibility_waiter(element_name, *find_args)
  method_name = "wait_until_#{element_name}_visible"
  create_helper_method method_name, *find_args do
    define_method method_name do |timeout = Waiter.default_wait_time, *runtime_args|
      Timeout.timeout timeout, SitePrism::TimeOutWaitingForElementVisibility do
        Capybara.using_wait_time 0 do
          find_options = find_args.last.is_a?(Hash) ? find_args.pop : {}
          runtime_options = runtime_args.last.is_a?(Hash) ? runtime_args.pop : {}
          options = find_options.merge(runtime_options).merge(visible: true)
          sleep 0.05 until element_exists?(*find_args, *runtime_args, options)
        end
      end
    end
  end
end
```

Note that not only `create_visibility_waiter` has this issue. `create_existence_checker`, `create_nonexistence_checker`, `create_waiter`, and `create_invisibility_waiter` have the same issue.

**Comment by luke-hill** [comment]
Hi there. You've found an interesting issue. But before this gets re-prioritised can I just ask you to confirm this is still and issue (Issue is nearly a year old).

Also can you provide an SSCCE for me to test against with an example of where the code is falling over.

Alternatively, if you're happy landing the PR yourself (Alongside the Test page), then feel free to do so.

Thanks for the report

**Comment by luke-hill** [comment]
Re-open a new issue if still present
