### ISSUE TITLE
2.10 release?

### ISSUE THREAD

**Issue by markpfletcher** [natritmeyer/site_prism#182]
Is 2.10 going to be released soon? The HISTORY file references 2.10 but it's not released yet.
We are currently using the git master branch for this gem and it would be great to move to 2.10 instead.

**Comment by natritmeyer** [comment]
Yeah, I should do that.

BTW, nice avatar. Brings back memories :)

**Comment by luke-hill** [comment]
Any news on this, even judging by the release history a 2.9.1 is probably more appropriate if you've not added any new functionality

It would probably be worth cutting a 2.9.1 even if the quantity of changes is minimal just to remind people this is still being maintained? @natritmeyer

**Comment by natritmeyer** [comment]
Will spend some time this weekend getting ready for a release

**Comment by luke-hill** [comment]
Prod (I know there's only been 12 commits to master in over 15months. But it's still doing something to show there is some limited development - @natritmeyer

Maybe look into giving other people pull access. I know (Deliberately not tagging), tmertens is quite active in here (Relatively speaking)

**Comment by natritmeyer** [comment]
That's not a bad idea. I'm swamped with other stuff and though I keep meaning to catch up it's just not feasible at the moment (2 kids under 2 years old :/ ). @tmertens Are you keen?

**Comment by luke-hill** [comment]
As this fell by the wayside, I'm happy to volunteer my own efforts to maintaining this gem. I will only be working within my means, But I'm capable of doing the Rubocop / Going through the Pull Requests if so desired?

@natritmeyer if you want to chat more you can send me an email? lukehill_uk@hotmail.com if thats helps?

**Comment by natritmeyer** [comment]
Thanks for the offer. I'll send you a mail.
