### ISSUE TITLE
Cannot use load validations without giving page a URL

### ISSUE THREAD

**Issue by TimKilcullen** [natritmeyer/site_prism#183]
In the README under the 'Adding a URL' section it states that adding a URL is optional, but it appears that if you don't add a URL, you will always get an exception `SitePrism::NoUrlMatcherForPage` when attempting to use load validations. It looks like this is because every page gets a default `displayed?`  load validation. Should this default load validation even be added if a URL is not set for a page?

**Comment by natritmeyer** [comment]
Good point. I'll take a look 👍

**Comment by tmertens** [comment]
> Should this default load validation even be added if a URL is not set for a page?

The default validation should probably just return true if there is no URL set.

**Comment by luke-hill** [comment]
Closing in favour of PR (Now reviewed)
