### ISSUE TITLE
How can a dynamically change my element name?

### ISSUE THREAD

**Issue by Karueglazki** [natritmeyer/site_prism#187]
I want to create a method with parameters and then create a element depends on parapets
I want to do something like this
class test_4 < SitePrism::Page
 def concepts (name)
     element :check_#{name}, :xpath, "//li[contains(.,'#{name}')]/input"
     element :score_#{name}, :xpath, "(//input[@name='#{name}_score'])[1]"
     element :rank_#{name}, :xpath, "(//input[@name='#{name}_rank'])[1]"
 end

**Comment by luke-hill** [comment]
This is very high end meta-programming. In it's current guise I disagree with this approach. Similar items can be coded in this way

Furthermore in a core ruby approach you can metaprogram this stub in to extend SP at runtime to dynamically create your sections with different names (Not sure about interpolated names)
