### ISSUE TITLE
Infinite loop in page.rb:find_all

### ISSUE THREAD

**Issue by tucknats** [natritmeyer/site_prism#189]
I initially opened an inquiry with the Capybara team thinking it was an issue there but Tom Walpale suggested that this is becuase site_prism overwrote the capybara find_all method. So, here's the problem,

page.rb from site_prism
   def **find_all**(*find_args)
      all(*find_args)
    end

and matcher_proxies.rb from capybara
def all(*args)
      if defined?(::RSpec::Matchers::BuiltIn::All) && args.first.respond_to?(:matches?)
        ::RSpec::Matchers::BuiltIn::All.new(*args)
      else
        **find_all**(*args)
      end
    end

This keeps falling in the else block and goes back to the find_all from site_prism page.rb. Here's a link to the discussion on Capybara group,

https://groups.google.com/forum/#!topic/ruby-capybara/VuFI7FDEp5Y

**Comment by tucknats** [comment]
@natritmeyer  any thoughts? This is affecting us big time.

**Comment by luke-hill** [comment]
Hi @tucknats This is an issue which I've personally encountered. Essentially you're likely getting a name Collision.

One way to mitigate this is to create a custom RSpec matcher for `all` possibly with a slightly different name.

An SSCCE to do this would be something like this
```
module CustomMatchers
  def all_match(item)
    RSpec::Matchers::BuiltIn::All.new(item)
  end
end
```
