### ISSUE TITLE
Clicking a link that does not have a name

### ISSUE THREAD

**Issue by esciara** [natritmeyer/site_prism#190]
Hi,

I am trying to find a way to verify that a link element exists in a page and then click it... But the link does not have a name, or anything else but the text to identify it:
```
    <div class="aui-panel setup-success">
        <a class="finishAction aui-button aui-button-primary setup-button" href="/">
            Start
        </a>
        [..]
    </div>
```
Since I cannot use an equivalent of Capybara's `click_link 'Start'`, as explained in issue #10 ,
I tried with success `element :start_link, "a[href='/']"`, which is found when calling `my_page_object.has_start_link?` ... But I don't find it safe enough.

I tried `element :start_link, "a.setup_button[href='/']"` or `element :start_link, "a[class~='setup-button'][href='/']"` following the info I found on https://www.w3.org/TR/CSS2/selector.html (link found on [this stackoverflow thread](https://stackoverflow.com/questions/12220310/can-you-find-elements-by-id-title-link-etc-through-site-prism-or-only-by-css-sel)) but it doesn't work. 

What would be an equivalent of this? (I googled it without success...)

**Comment by distortia** [comment]
Can you do something similar to `element :start_link, 'a', text: 'Start'` ?

**Comment by luke-hill** [comment]
Suggestions have been mooted. Look at w3c schools - https://www.w3schools.com/css/css_pseudo_elements.asp maybe as a starting point
