### ISSUE TITLE
Is there a way to refresh the page elements & sections?

### ISSUE THREAD

**Issue by barodapride** [natritmeyer/site_prism#191]
I'm running into an issue where I'm getting a StaleElementException when trying to access one of my siteprism sections. I believe this could be solved by refreshing the page elements & sections. Is there a method to do this? I read up on the exception and it seems like it's caused when the node/element gets reparented to a new element.

**Comment by luke-hill** [comment]
Siteprism does not cache page objects. SO if you require an object to be reassigned. reinstantiate your page/ancestral tree
