### ISSUE TITLE
Nodes cached in sections

### ISSUE THREAD

**Issue by garytaylor** [natritmeyer/site_prism#192]
I am having issues with nodes being cached (@root_element) in sections.  The problem with this is when capybara is doing its stuff - retrying whilst looking for things etc..  and the page is changing underneath it (say some JS) then the node is no longer there and you get a stale node error - or obsolete node error (phantomjs).

I wrote a page object library in the days when this library was a little bit short of features and one thing I learned was to never store any nodes - instead store how you got to that node so that it can be re fetched every time

**Comment by luke-hill** [comment]
Not really an issue, so closing.

Not quite sure what you're asking. The `root_element` parameter is set at point of instantiation. And only cached on a per object basis. If your physical `section` is being mutated (Which shouldn't really happen in sections), then you could potentially come unstuck. Advise you to select `sections` which are unmutable or at a granular enough level such that they don't mutate at the level defined. You can always reinstantiate the object?

On a side situational note. phantomJS is slowly being phased out of existence, and if you're running our tests through a browser automation framework, it is advised as best practice currently (And will later become the **only** practice) to use a native Browser Headless Design (Which is fully formed for Chrome and I believe fully formed for Firefox under Gecko)
