### ISSUE TITLE
iframe not working with xpath

### ISSUE THREAD

**Issue by zwarburg** [natritmeyer/site_prism#230]
# Issue to raise for SitePrism framework
Before raising an issue with us please ask yourself whether you have all the information available to advise us.

For us to try to help you with your issue, we require certain information. Please replace each of the bullet points with your **own** input.

## Environment
- Operating System: Windows
- What Gems / Versions you are using:
-- Capybara: 2.18.0
-- Site_prism: 2.11
- How you're interacting with the Framework: Rspec/cucumber

## Expected Behavior
Trying to use iframes with an xpath.

## Actual Behavior
```
Failure/Error: iframe :details, PageObjects::Pages::Details,  :xpath, "//div[@id='iframe_div']/iframe"

ArgumentError:
  wrong number of arguments (given 4, expected 3)
```

**Comment by luke-hill** [comment]
Just as a bump to the original author. A couple of the committers / reviewers are currently away (I've just come back myself). So this might take a bit longer to look at.

From initial glance you do seem to have provided a simple case to triage. So we'll be in touch soon

**Comment by twalpole** [comment]
Support for selector types with `iframe` wasn't added until after the 2.11 release - https://github.com/natritmeyer/site_prism/commit/296c932409fb51484d2897a0283dfaf6baa0645b - so you'll either need to use the master branch or wait for the next release

**Comment by luke-hill** [comment]
Cheers @twalpole. @zwarburg this should be working (In the latest master). The work to support this has already gone in with https://github.com/natritmeyer/site_prism/pull/215 - Referenced directly in the commit by Thomas above.

The next cut of the site_prism code will be happening shortly. Just wanted to get a bit more dev refactoring done before we do cut it (Probably some time in the next week or so)

Closing as already fixed.
