### ISSUE TITLE
*_visible method doesn't work as documented 

### ISSUE THREAD

**Issue by rodrigovrm** [natritmeyer/site_prism#246]
## Environment
- Operating System (Mac / Windows / Ubuntu e.t.c.)

mac 

- What Gems / Versions you are using (Specifically `site_prism` and `capybara`)

site_prism 2.9
capybara 2.13.0

- How you're interacting with the Framework (Cucumber Tests / RSpec Units / Minitest)

rspec

- Browser/s Driver/s being used - with version numbers

webkit

## Expected Behavior
According to the documentation here: https://github.com/natritmeyer/site_prism#methods-supporting-capybara-options I should be able to do this

```
class CreateJobPage < SitePrism::Page
  element :items_modal, '.modal'
end

...
@create_job_page.wait_until_items_modal_visible text: 'Job name'
```

## Actual Behavior

```
NoMethodError:
       undefined method `zero?' for {:text=>"Job name"}:Hash
     # /Users/rra/.asdf/installs/ruby/2.3.4/lib/ruby/2.3.0/timeout.rb:74:in `timeout'

```

**Comment by tgaff** [comment]
@rodrigovrm  - can you add the full stack trace please?

**Comment by luke-hill** [comment]
We require a full reproduction scenario to try diagnose this. These kind of tests are readily covered in both Unit Tests and Integration tests, so we'd need to understand how you are generating this issue
