### ISSUE TITLE
Use of Timeout.timeout is a problem

### ISSUE THREAD

**Issue by twalpole** [natritmeyer/site_prism#257]
Because of the way it works `Timeout.timeout` is the most dangerous method in Ruby and should only be used around code that is trivial, completely understood and guaranteed to be safe for a random exception to occur at any point in its execution, or that blocks those exceptions using `Thread.handle_intterupt`.  SitePrism has two places where it wraps Capybara calls with `Timeout.timeout` including
https://github.com/natritmeyer/site_prism/blob/9c39f4b3b8ba47427a34b7b0cccd2a527c920f51/lib/site_prism/element_container.rb#L180 which can cause drivers to end up in unrecoverable states if the timeout ever occurs.

**Comment by twalpole** [comment]
Note: this still has the issue that the `find_args` and `runtime_args` won't get combined correctly, but that's a problem in all the ElementContainer methods and should probably be fixed in a separate PR

**Comment by luke-hill** [comment]
Closing in favour of PR
