### ISSUE TITLE
SitePrism approach towards Selenium::WebDriver::Error::StaleElementReferenceError

### ISSUE THREAD

**Issue by matisnape** [natritmeyer/site_prism#267]
# Issue to raise for SitePrism framework
Need information on how to handle Selenium::WebDriver::Error::StaleElementReferenceError

## Environment
- Operating System : Mac
- site_prism: 2.13, Capybara 2.18
- Rspec 3.7.0 - e2e tests
- Chromedriver: 2.40

## Expected Behavior
Test not failing.

## Actual Behavior
I have the following spec:
```
feature 'Changing job status' do
  let(:jobs_page) { JobsPage.new }
  let(:status) { jobs_page.status_list }
  let!(:job) { api.jobs.create_job }

      scenario "shows a modal and updates status on the list to published" do
        login_with_token
        jobs_page.load
        jobs_page.has_job_items?(count: 1)
        expect(jobs_page.job_items[0]).to have_status(text: 'Draft')
        jobs_page.set_status("published", job["title"])
        # Selenium::WebDriver::Error::StaleElementReferenceError:
        # stale element reference: element is not attached to the page document
        # https://www.seleniumhq.org/exceptions/stale_element_reference.jsp
        expect(jobs_page.job_items[0]).to have_status(text: status[:published], wait: 15)
      end
    end
end
```

Basically I'm changing a job item status. The test was passing, but since frontend refactor (which is done in Angular), on the last assertion I keep getting `Selenium::WebDriver::Error::StaleElementReferenceError: stale element reference: element is not attached to the page document`. However, when I put binding.pry before that last expect, and paste it inside console, the assertion returns true. 

I've read this https://www.seleniumhq.org/exceptions/stale_element_reference.jsp so I know what happens, but I don't know how to handle this in my test properly. 
I've looked on SO for similar issues, and Watir for instance handles this like that: https://stackoverflow.com/questions/35000404/ruby-unable-to-catch-seleniumwebdrivererrorstaleelementreferenceerror - the link to exact code doesn't work anymore, but I believe this is it: https://github.com/watir/watir/blob/master/lib/watir/elements/element.rb#L578

How can I force re-locating the lost reference/element in SitePrism? What's the advised approach towards this kind of issues if I don't have influence on the app I'm testing on?

## Steps to reproduce
Unfortunately, I cannot prepare a reproducible example, because I'm not a developer.

**Comment by luke-hill** [comment]
Couple of observations on your spec

```
        jobs_page.has_job_items?(count: 1) # This will not actually do anything, it will just return true or false.
```

It is likely you want a waiter in here.

```
        expect(jobs_page.job_items[0]).to have_status(text: 'Draft') # This spec could be flaky?
```

```
        jobs_page.set_status("published", job["title"]) # Not familiar with this API. Are you using selenium. If not can you tell me how this method works.
```

**Comment by matisnape** [comment]
@luke-hill 
the first line you mentioned is making sure that I have one item on job_items list - I use this query option as a waiter, because the siteprism waiters for sections inside sections didn't work (I know there's been a fix, but I haven't had the chance to check that yet- I've just changed my approach to use capybara query options).

the second line actually works without problems, it's the last expect that is flaky due to stale reference - after consulting with developer I know that this happens because part of the component I'm relying the reference on is disappearing and reappearing with new data - is rendered again into the DOM, if you will. Adding a `sleep 1` prevents this error, but this is not solving the issue itself and it also slows down the test run. 

As for  the third line - I have a `set_status` method in my page object. Actually, there are even more methods that go into `set_status` :)

```
  def set_status(status, for_job)
    click_element_of_job(:status, for_job)
    status_select.public_send(status).click
    modal.confirm
    has_no_status_select?(wait: 15)
    notification_list.send("has_#{status}?")
    notification_list.send("has_no_#{status}?")
  end

  def jobs_list
    jobs_list = []
    job_items.map { |item|
      jobs_list << item.title.text
    }
    jobs_list.flatten
  end

  def job_index(title)
    jobs_list.index(title)
  end

  def click_element_of_job(element, job_title)
    job = job_items[job_index(job_title)]
    job.public_send(element).click
  end
```

**Comment by luke-hill** [comment]
If you can reproduce a SSCCE I'll take a look at this to see if there is an issue our end. I'm reasonable confident there isn't though.

If you're getting a stale element reference it means that you are pre-caching your query (RSpec Let blocks can pre-cache things at weird intervals).

If you can reproduce this error inside an it block where you are confident nothing is being pre-cached let me know.

**Comment by matisnape** [comment]
There's no problem with SitePrism here, but I was curious if I can work around this error. 
Can I force RSpec not to pre-cache a certain element or force refreshing the cache?

**Comment by luke-hill** [comment]
In an individual spec, yes you can.
In a multi-spec, no you can't (Not without using dual variables)

`let` only calls the element for the first time on invocation. It's basically a memoization method.
