### ISSUE TITLE
Add Dual Gemfile testing

### ISSUE THREAD

**Issue by luke-hill** [natritmeyer/site_prism#278]
More of a placeholder for a new piece of work if you're interested @RustyNail.

We're about to start offering some limited Capybara 3 support. Do you want to amend travis to partition our tests into a test that runs on Capybara 2.18, and one that runs on the latest version supported (Restricted by our gemspec)

If not I'll try pick this up as and when.

As part of this work, all you need to change is travis. All work to ensure Capybara3 works across our codebase is already being handled and will be merged in before your code changes (So don't worry about passing builds e.t.c. just yet)

**Comment by bmulholland** [comment]
On the off chance that you haven't seen the project already, I've used https://github.com/thoughtbot/appraisal for this in the past. Very easy to set up and use.

**Comment by luke-hill** [comment]
That is quite a large scale involvement probably for production style items @bmulholland 

This issue would be just to implement a dual gemfile. Which travis can then load in through its matrix to run tests against. In all honesty, using the travis implementation is only 1-2hours work max.

If you're keen on doing the travis implementation as I've not heard from @RustyNail then go for it. Any help is greatly appreciated

**Comment by luke-hill** [comment]
Fixed in https://github.com/natritmeyer/site_prism/commit/dec4c64396ca74fb7ad1884884204f78bd5b05ff
