### ISSUE TITLE
Update gem to use the newest capybara

### ISSUE THREAD

**Issue by DamirNurgaliev** [natritmeyer/site_prism#287]
Hi!

Your gem has a dependency with [capybara gem](https://github.com/teamcapybara/capybara) which locked by 3.0.3 version, but the newest one is **3.3.1**. Can you make an update, please?

**Comment by luke-hill** [comment]
We've literally just released a cut (v2.15), which unlocked capybara to version 3.

Firstly we want to ensure this hasn't broken things, and we haven't missed something before increasing the restrictions more. Rest assured that we will allow more versions of capybara as and when we get round to updating.

See: https://github.com/natritmeyer/site_prism/pull/277 for the initial comments and https://github.com/natritmeyer/site_prism/issues/242 / https://github.com/natritmeyer/site_prism/issues/268 / https://github.com/natritmeyer/site_prism/pull/264

**Comment by luke-hill** [comment]
v2.15.1 due to be released sometime in the next week will permit higher versions of capybara
