### ISSUE TITLE
Where to put section files

### ISSUE THREAD

**Issue by mbajur** [natritmeyer/site_prism#294]
## Environment
- macOS
- site_prism 2.15 / capybara 3.0.3
- rspec
- chromedriver 2.40.565386

## Expected Behavior
Section classes seeing each other and be seen by Page instances

## Actual Behavior
I'm not sure where to put the section definitions. All my page definitions are in spec/support/pages which is autoloaded by rails_helper. However, adding `sections` directory there and putting my section definitions there results in "unitialized constant <ClassName>" errors thrown by pages.

I tried taking the prism code out of support directory (now they are in `spec/page_object/pages` and `spec/page_object/sections`) to take control of require order and it seemed to work locally but, on my CI setup, im getting one exception per each spec file (even if that file is not using the page_prism) complaining that i'm trying to use, say, `SecondSection` in `FirstSection` (the error is thrown in `FirstSection` and says that `SecondSection` is an unitialized constant).

The reason for this is wrong order of require of the section classes so they don't know about each other but i'm not really sure on how to improve that nor why the hell they are initializing the section objects on require - it shouldn't behave like that afaik.

To require my site_prism stuff, i'm using following code in rails_helper.rb

```
require 'site_prism'
Dir[
  Rails.root.join("spec/page_objects/sections/**/*.rb"),
  Rails.root.join("spec/page_objects/**/*.rb")
].each {|f| require Rails.root.join(f)}
```

## Steps to reproduce
It's mostly about running it on test environment, you can see an example failing spec here: https://gitlab.com/mbajur/prismo/-/jobs/83171464

**Comment by luke-hill** [comment]
From initial triage this seems to be a user-error. The way ruby works is that you need to define things backwards. I.e. most granular classes (Small Sections), then less granular classes (Larger Sections / Pages)

i.e.

```
require_relative 'smallest_section'
require_relative 'medium_section'
require_relative 'my_page'
```

For

```
class MyPage < SitePrism::Page
  section :medium_section, MediumSection, 'med-sect'
end

class MediumSection < SitePrism::Section
  section :smallest_section, SmallestSection, 'small-sect'
end

class SmallestSection < SitePrism::Section; end
```

if you can upload a sample script that fails to execute then please do so. I've only had a quick look at the job but it doesn't show me your source code. If you can produce us an SSCCE then we'll triage further.

**Comment by mbajur** [comment]
yes, that's exactly what i'm trying to do - to load it "granularly" but without specifying each require by hand. I would love to auto-load all the sections just like all the pages are auto-loaded.

Does using the require snipped i used:

```
Dir[
  Rails.root.join("spec/page_objects/sections/**/*.rb"),
  Rails.root.join("spec/page_objects/**/*.rb")
].each {|f| require Rails.root.join(f)}
```

should theoretically work out of the box and prism sections should don't care about the order or there are some internals in site_prism i don't know about ? If so, this issue can be safely closed as it seems to be an issue with my setup rather than with site_prism

**Comment by luke-hill** [comment]
Or if you want a really "quick" way.
A -> Have a folder of all of your bottom level sections (i.e. sections which don't call other sections).
B -> Have a folder of all of your other sections (That only call sections defined in **A**)
C -> Have a folder of all of your pages **(Already done)**

**Comment by mbajur** [comment]
Thank you! I'm definitely gonna use one of these approaches :)
