### ISSUE TITLE
Recent releases are dated to year 2015 in HISTORY.md

### ISSUE THREAD

**Issue by JaniJegoroff** [natritmeyer/site_prism#306]
Releases from 2.11 and forward are dated to year 2015 in HISTORY.md
```
HISTORY.md

2.15.1 - 2015-07-20
...
2.11 - 2015-03-07
2.10 - 2018-02-23
```

**Comment by luke-hill** [comment]
Good spot. If you're able to fix these up as a minor patch branch feel free. Otherwise I'll get to it when I can.

I'm currently without a satisfactory dev environment for a few days (Although I might end up setting up a VM at home), so if you can fork this and make a PR I'll review it asap

**Comment by luke-hill** [comment]
Closed in https://github.com/natritmeyer/site_prism/commit/d571daba902e29082eff19830ce4acc5b272d01e
