### ISSUE TITLE
Create #wait_until_displayed? - standardise #displayed? method

### ISSUE THREAD

**Issue by luke-hill** [natritmeyer/site_prism#318]
The second iteration of small cleanup tasks for the SitePrism repo.

This one is only a 1liner, but is potentially trickier.

- SitePrism has a `displayed?` method. But we should really have a waiter method as well. Ideally these two methods should be standardised so the logic lives in the Waiter and then the displayed? method simply rescues the timeout.

See `page.rb` for where to code is consumed.

Pitfalls to watch out for
- Once you've moved the code and made the `displayed?` method just call the waiter method. Make sure both methods are publically usable, and write tests accordingly.

**Comment by bananaumai** [comment]
@luke-hill Would i tackle this issue?

**Comment by luke-hill** [comment]
Feel free @bananaumai - It's an Open Source project. Anyone is welcome to contribute.

**Comment by bananaumai** [comment]
> See https://github.com/natritmeyer/site_prism/blob/master/.github/CONTRIBUTING.md for tips.

thanx!

**Comment by luke-hill** [comment]
I've got a bit of time free and was going to clear some of these off.

@bananaumai did you ever get around to tackling this? Not heard from you in 6+ weeks

**Comment by jgs731** [comment]
All yours if you want to pick it up @bananaumai , otherwise I'll have a go if not

**Comment by bananaumai** [comment]
@luke-hill / @jgs731 sorry for long absense!
I haven't done anything about it... I don't have much time to tackle this now, so please take it, sorry @jgs731

**Comment by luke-hill** [comment]
Any updates on this from anyone?

**Comment by TheSpartan1980** [comment]
> Any updates on this from anyone?

@luke-hill I wouldn't mind taking a shot at this, I can't promise anything stellar but I'd love the opportunity

**Comment by luke-hill** [comment]
@TheSpartan1980 if said you posted here, if you are listening go for it. It's open source, anyone is welcome

**Comment by TheSpartan1980** [comment]
@luke-hill I've made a start, but I think I could do with some of your guidance if you have capacity to provide it?

**Comment by luke-hill** [comment]
@TheSpartan1980 push something up as a draft pr

**Comment by luke-hill** [comment]
Present in master
