### ISSUE TITLE
Improve Feature Coverage - Loadables

### ISSUE THREAD

**Issue by luke-hill** [natritmeyer/site_prism#321]
Create a new set of feature tests that validate loadable tests work and do wait for things to change.

Pitfalls to watch out for
- When adding these tests in, make sure the loadable has both positive and negative tests (for waiting for things too fast/slow)
- Ensure that we're not modifying the overall page behaviour (Might need new page)

**Comment by luke-hill** [comment]
ping @dgarwood. Think you mentioned you wanted to tackle some tickets.

This one or the other ones with Good for Newcomers are worth a shot if you're interested.

**Comment by dgarwood** [comment]
@luke-hill I'll see what I can tackle.

**Comment by dgarwood** [comment]
@luke-hill I don't have anything I can push at the moment.

**Comment by luke-hill** [comment]
Closed by https://github.com/natritmeyer/site_prism/pull/363
