### ISSUE TITLE
Ability to check expected elements for section or page recursively

### ISSUE THREAD

**Issue by faceless7171** [natritmeyer/site_prism#338]
## Expected Behavior
It would be great to have ability to run method all_there? recursively in the specified section or page.

The solution can look something like this:
```
  module ElementChecker
    def all_there_r?
      elements_to_check.each do |e|
        if self.send(e).respond_to?('all_there?')
          self.send(e).all_there_r?
        end
      end
      self.all_there?
    end
  end
```

**Comment by luke-hill** [comment]
Sounds like a good idea for a new feature I agree. Just to clarify a few points / ideas.
#1 - I am on a page which has sections / elements and I run `all_there_r?`
- I first of all check every item that is mapped - If that's true. I then build a list of all section / sections
- For each section, I run `all_there?`

#2 - How would you define the limit of recursiveness (Would it be infinite>?)

#3 - Are you wanting to discuss this / implement this, the code you've mentioned seems ok, but obviously I'm not behind my terminal at the moment.

**Comment by faceless7171** [comment]
1. For my understanding it should check only expected elements, not mapped ones (they will be equal if expected_elements is not specified). So for the page like this:
```
class Home < SitePrism::Page
  set_url '/index.htm'
  set_url_matcher /google.com\/?/

  section :s1, 's1' do
     element :e1, 'e1'
     element :e2, 'e2'
     section :s2, 's2' do
       element :e3, 'e3'
       element :e4, 'e4'
       element :e5, 'e5'
       sections :s3, 's3' do
         element :e6, 'e6'
       end
       expected_elements :e4, :e5, :s3
     end
  end
  element :e7, 'e7'
end
```
If I will run all_there_r? on this page it should check existence of:
      s1.e1, s1.e2, s1.s2, s1.s2.e4, s1.s2.e5, s1.s2.s3, e7

Also I'm think that it is not possible to check existence of elements in "sections", we can only check that this sections are present. But I can be wrong here.

2. I'm fine with infinite recursiveness, but it would be great if we will have possibility to change the limit.

3. I'm pretty new to ruby, so I'm afraid I can't implement this feature. My code example is working only for the simplest case in my project.

P.S. I don't have any ideas of how to name this method :) Possibly we can improve existing "all_there?", and it will run recursively by default, will have arguments with recursive limit it it?

**Comment by luke-hill** [comment]
Thanks for the updates. I've got some ideas about how to start with this. Will probably put something up in 3.1 in the next couple of weeks.

**Comment by luke-hill** [comment]
I've got something which may land in a week or so (Spec refactor took a bit longer), which should allow for some small recursion to happen. Watch this space.

**Comment by luke-hill** [comment]
I've got an interim piece of code for this. But it's not really doing anything yet. I'll get something better up on a branch for you to have a play with sometime in December. @faceless7171

**Comment by luke-hill** [comment]
I've got some initial work that will hit a 3.0.1 release that will lay the foundations for some of this.

If you're interested in contributing at all let me know

**Comment by luke-hill** [comment]
I've pushed up a branch with some of the boilerplate @ineverov which relates to this Feature Request. Check it out if you want.

**Comment by tgaff** [comment]
Hi @luke-hill I was wondering what ended up happening with your recursive `all_there?` branch?  We have an engineer who's interested in using that functionality.

**Comment by luke-hill** [comment]
https://github.com/natritmeyer/site_prism/tree/feature/all_there_recursion_struct - This doesn't actually recurse yet. But it does set all the boilerplate, all of the unit tests plus the additional logging / documentation

**Comment by luke-hill** [comment]
An initial cut of this is now in master.
