### ISSUE TITLE
wait_for_<section> not working in 3.x

### ISSUE THREAD

**Issue by peetar** [natritmeyer/site_prism#339]
## Environment
-  Mac
- site_prism 3.0, capybara 3.10.1
- Using rspec
- selenium-webdriver 3.141.0, chrome Version 70.0.3538.77

## Expected Behavior
We are adding widgets to a page through some asynchronous  javascript. They are each defined as a section:
`sections :basic_widgets, ::EasyFormsSection::BasicWidget, ".widgets .widget"`
Previously, the following code allowed us to wait for the widget to appear after each click:
`page.wait_for_basic_widgets(nil, count: 1)`

## Actual Behavior
```
undefined method `wait_for_basic_widgets' for #<EasyFormsPage::Edit:0x00007f88d5cfd3d8>
       Did you mean?  wait_for_attached_list
```
So it can't find the section and instead looks for an element

## Steps to reproduce
try wait_for_ with any section instead of an element
If this is intended behavior, I'd love some help with a workaround. We've followed this pattern extensively through our test suite.

**Comment by ineverov** [comment]
@peetar it was removed in site_prism 3.beta https://github.com/natritmeyer/site_prism/blob/master/HISTORY.md#removed-1
use ```page.wait_until_basic_widgets_visible(count: 1)``` instead

**Comment by peetar** [comment]
I must have got those two methods confused, thanks, I believe we use wait_until_visible most of the time, so I might only need to update a few tests using deprecated method

**Comment by luke-hill** [comment]
Also for reference, we now always use the implicit waiting logic defined by Capybara.

So if you just call `basic_widgets` it will wait the `Capybara.default_wait_time`.

However should you not want this, you can turn it off (Set the default_wait_time to 0), and call a wait key in-line.

i.e. `basic_widgets(wait: 3)`, this will always wait up to 3 seconds.

Essentially Site Prism now mirrors Capybara much closer, and allows you a greater level of control (Once you upgrade to v3)
