### ISSUE TITLE
newbie question about elements

### ISSUE THREAD

**Issue by jampow** [natritmeyer/site_prism#343]
Hi,

I'm trying to dynamically select an element. It works well if I type `@mypage.myelement`, but when I try `@mypage[:myelement]` or `@mypage["myelement"]` it gives me the error: `undefined method '[]' for #<MyPage:0x000055e0be333728> (NoMethodError)`.

A simple example to simulate the error could be like this:

```
name = :myelement
@mypage[name]
@mypage[name.to_s]
```

**Comment by ineverov** [comment]
@jampow It's Ruby question not site_rism. @mypage is a class and `myelement` is a method in this class. You cannot call a method with brackets by default. If you want to do this you can use `send` method.
```
name = :myelement
@mypage.send(name) # or
@mypage.send(name.to_s)
```
It might be possible to alias `[]` to `send` though
@luke-hill What do you think about it? We might combine this with other potentially useful feature I was thinking about.

1. Store available elements, section names to an array. So it's easy to inspect the structure of the element container
```
> MyPage.new.structure 
< [:a, :b, :c, d: [:e, :f]] 
```

2. define `#[]` to be
```
def [](name)
   send(name) if structure.include?(name)
end
```

**Comment by jampow** [comment]
Hi @ineverov, tks... I will study more ruby. ^^

**Comment by luke-hill** [comment]
the available element names are already found via `mapped_items`. It's not quite in the structure you mentioned, but it's kinda there.
