### ISSUE TITLE
Add not_expected_elements function for a page/section class

### ISSUE THREAD

**Issue by faceless7171** [natritmeyer/site_prism#344]
Right now we can specify expected_elements for a page/section class. It would be great if we will have ability to specify elements that we are not expecting to see on the page by default.

Expected behavior:
 ability to add elements/sections on the page/section description to the not expected elements, so be_all_there matcher will ignore this elements/sections.

Example:
```
class Home < SitePrism::Page
  set_url '/index.htm'
  set_url_matcher /google.com\/?/

  section :s1, 's1' do
     element :e1, 'e1'
     element :e2, 'e2'
     section :s2, 's2' do
       element :e3, 'e3'
       element :e4, 'e4'
       element :e5, 'e5'
       sections :s3, 's3' do
         element :e6, 'e6'
       end
     end
  end
  element :e7, 'e7'
  
  not_expected_elements :e2, :e7
end
```

Then `expect(HomePage).to be_all_there` will check only existence of e1, s2 elements.

**Comment by luke-hill** [comment]
we have `expected_elements` declaration defined here: https://github.com/natritmeyer/site_prism#checking-that-all-mapped-elements-are-present-on-the-page

Whilst the definition you've provided kind of offers the functionality, the original author found difficulties and as such inverted the logic to instead specify only the items that "should" be on the page.

Whilst you have another feature request open, be wary that until this is implemented, in your example `#all_there?` currently on your example would only search for s1 and e7. so e2 wouldn't be a defined checked value for `#all_there?`

**Comment by faceless7171** [comment]
Yes, understood, initial example was not correct, sorry for that :)
**Corrected example:**
```
class Home < SitePrism::Page
  set_url '/index.htm'
  set_url_matcher /google.com\/?/

  element :e1, 'e1'
  element :e2, 'e2'
  section :s2, 's2' do
     element :e3, 'e3'
     element :e4, 'e4'
     element :e5, 'e5'
     sections :s3, 's3' do
        element :e6, 'e6'
     end
  end
  element :e7, 'e7'
  
  not_expected_elements :e2, :e7
end
```
Then `expect(HomePage).to be_all_there` will check only existence of e1, s2 elements.

**Comment by luke-hill** [comment]
Seems logical. We could create the inverse of this, but it's primarily about ensuring that we don't break previous compatibility, we also would want some sort of warning when both are set.

Does `expected_elements` not fulfill your purpose?

**Comment by faceless7171** [comment]
When we have a big page with a lot of elements and by default we don't expect to see just couple of elements, we need to list all expected elements in order to achieve this functionality. Later such pages descriptions can be hard to maintain. For me `expected_elements` logic should be default on the page and include all elements (all elements described on the page are expected), and only if  we will specify `not_expected_elements`, then not expected elements will be excluded from expected elements list. I think this is  more straightforward page description.

**Comment by luke-hill** [comment]
Fair point. I'll have a think about this because the way in which we store / query elements is very archaic and should probably be refactored extensively.

**Comment by tgaff** [comment]
Hey @luke-hill what became of your branch for this?  We have an engineer who's interested in using this for a bunch of regression testing work he's doing.

**Comment by luke-hill** [comment]
I actually looked at the other feature request first (recursion), as both of these were going to take some time.

I had a brief spike branch on this but I trashed it after it didn't work as I expected. I fully expect that this shouldn't be as much work as I was making it to be, so I decided just to quit and start again (Just not got round to starting it again)

Feel free to give it a tackle or convince him to have a go and push something up I'll review. The original work was done by @TheMetalCode so he might be interested in chiming in / reviewing it.

**Comment by luke-hill** [comment]
I've had another look into this, and actually this should be fairly easy to code. Because the current logic is as follows.

`@expected_items` Which is the instance variable representation of `expected_elements` simply is assigned values. But the values which are checked is the Intersection (Union), of `@mapped_items` and `@expected_items`

Given the above logic, this feature request simply request a 2nd methodology of creating the values to be checked by doing the Set Difference of `@mapped_items` and `@new_instance_variable`.

So in essence the raw code that would need to be implemented is 5-10 lines max. Obviously we'd need documentation, specs, features and possibly some sort of guard clause to prevent both being used. As this would inevitably cause some issues.

Given the above. Does one of you @tgaff / @faceless7171 feel like taking a shot at this?

**Comment by luke-hill** [comment]
ping @faceless7171 - tgaff is looking into another small issue. Is this something you wanted to look at to try get involved?

**Comment by luke-hill** [comment]
@faceless7171 any news from your side? Just going over the remaining outstanding issues on the old repo, this is still here.

**Comment by luke-hill** [comment]
Hi @faceless7171 - I'm using a bot to move these issues to the new main repo. Please can we continue the discussion over there. I'm keen on getting this implemented and can help you if needs be

**Comment by luke-hill** [comment]
Kamino closed and cloned this issue to [site-prism/site_prism](https://github.com/site-prism/site_prism/issues/23)
