### ISSUE TITLE
When I click on link, site prism get the link URL and concatenate with set_url "/en" and this broken

### ISSUE THREAD

**Issue by luizlohn** [natritmeyer/site_prism#357]
# Issue to raise for SitePrism framework
Before raising an issue with us please ask yourself whether you have all the information available to advise us.

For us to try to help you with your issue, we require certain information. Please replace each of the bullet points with your **own** input.

## Environment
- Operating System (Mac / Windows / Ubuntu e.t.c.) : Windows
- What Gems / Versions you are using (Specifically `site_prism` and `capybara`): Both
- How you're interacting with the Framework (Cucumber Tests / RSpec Units / Minitest): Cucumber
- Browser/s Driver/s being used - with version numbers: Chrome driver last

## Expected Behavior
What behaviour were you expecting?
When I click on link to change Language(its just a /en link) on normal browser its work and change for language

## Actual Behavior
What behaviour did you observe?
When I click on link to change Language the driver put a page error between base URL and Link
If you enter here: https://ferique-cd.azurewebsites.net/fr-FR/ and click on English to change its OK, will change, but when I do that through Capybara do not work

## Steps to reproduce
If you enter here: https://ferique-cd.azurewebsites.net/fr-FR/ and click on English to change its OK, will change, but when I do that through Capybara do not work.
If necessary I have a video

**Comment by luizlohn** [comment]
When I click on link, site prism get the link URL and concatenate with set_url "/en" and this broken

**Comment by luke-hill** [comment]
Hi @luizlohn please provide an SSCCE[www.sscce.org] so we can reproduce this issue.

Also can you advise the versions of all items you are using (site_prism, capybara, chrome), as requested in the report template. It's there to try help us.

**Comment by luizlohn** [comment]
I`m using site_prism,
PageObect:

`
class LoginFormSection < SitePrism::Section
element :user_field, '#loginEmail'
element :pass_field, '#loginPassword'
element :user_title, '.signin-form__form > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)'
element :pass_title, 'div.form-element:nth-child(2) > div:nth-child(1) > div:nth-child(1) > label:nth-child(1)'
element :submit_button, 'button.btn'
element :show_password, '.visibility'
element :forgot_credential, 'div.signin-form__form--helper:nth-child(4)'
element :forgot_user, 'div.signin-form__form--helper:nth-child(4) > a:nth-child(1)'
element :forgot_pass, 'div.signin-form__form--helper:nth-child(4) > a:nth-child(2)'
element :remember_me_text, 'div.signin-form__placeholder > div > form > div.signin-form__form--rememberme > div > div > label > span.input-label'
element :remember_me, 'div.signin-form__placeholder > div > form > div.signin-form__form--rememberme'
element :login_error, '#signin-form > div.signin-form__placeholder > div > form > div.input-group.show > span'
element :blocked_account_message, 'div.signin-form__placeholder > div > form > div.input-group.show > span'
element :recaptcha, '#recaptcha-anchor > div.recaptcha-checkbox-checkmark'
end

class RecoveryCredentialSection < SitePrism::Section
element :forgot_user, 'a:nth-child(1)'
element :forgot_pass, 'a:nth-child(2)'
end

class HeaderSection < SitePrism::Section
element :logo_image, 'img.nav__logo--image:nth-child(1)'
element :page_title, '.nav__plotline'
element :language, '#nav > ul > li.nav__lang'
end

class FooterSection < SitePrism::Section
element :footer, '#footer > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)'
element :footer_title, '.footer__plotline > span:nth-child(1)'
element :footer_week, '.footer__directions--workweek > span:nth-child(2)'
element :help_button, 'a.btn:nth-child(1)'
element :ferique_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(2) > a:nth-child(1)'
element :security_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(3) > a:nth-child(1)'
element :privacy_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(4) > a:nth-child(1)'
element :legal_notice_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(5) > a:nth-child(1)'
element :language_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(6) > a:nth-child(1)'
element :montreal_phone, 'li.footer__directions--sectiontitle:nth-child(2)'
element :toll_free_phone, 'li.footer__directions--sectiontitle:nth-child(3)'
element :send_message, 'li.footer__directions--sectiontitle:nth-child(4)'
end

class RequestAccessLink <SitePrism::Section
element :request_access_text, '.signin-component__footer'
element :request_access_button, '.signin-component__footer > a:nth-child(1)'
end

class SecurityPrivate <SitePrism::Section
element :request_access_text, '.signin-component__footer'
element :request_access_button, '.signin-component__footer > a:nth-child(1)'
end

class LoginPage < SitePrism::Page
set_url "/{language}"

section :login_form, LoginFormSection, '#signin-form'
section :recovery_section, RecoveryCredentialSection, 'div.signin-form__form--helper:nth-child(4)'
section :header_section, HeaderSection, '#nav'
section :footer_section, FooterSection, '#footer'
section :request_access, RequestAccessLink, '.signin-wrapper > div:nth-child(2)'
section :security_private, SecurityPrivate, '#secure-private'

end
`




I load the pageobject  with this code:
login_page = LoginPage.new 
login_page.load(language: ENV['LANGUAGE']) 
$header = login_page.header_section


In my test I use this expression to click:
$header.language.click

But when I click driver get the link and put set_url "/{language}" again together link and this broken

**Comment by luke-hill** [comment]
Can you re-read the requirements of the SSCCE. This is an awful lot of code for a login failing.

Can you only include the items that are needed, ideally in a git repo I can download with instructions to reproduce the bug.

**Comment by luke-hill** [comment]
@luizlohn still awaiting a response for this. I'll close it in a week if I don't hear back from you

**Comment by luke-hill** [comment]
Re-open as SSCCE if the problem still persists on version 3
