### ISSUE TITLE
Can not use rspec expect inside page object method

### ISSUE THREAD

**Issue by serhatbolsu** [natritmeyer/site_prism#371]
Can not use `expect` inside page object method.

## Environment
- Mac, rspec 3.8 , capybara 3.13, site_prism 3.0.3
- Rspec as framework

## Expected Behavior
I would like to use `expect` frases inside page object, method

## Actual Behavior
I get, 
```
undefined method `expect' for #<SignupPage:0x00007fa51a183370>
```

## Steps to reproduce
```
# home_page.rb
class SignupPage < SitePrism::Page
  set_url '/join'

  element :username, 'Username'
  element :email, 'Email'
  load_validation { has_username? }

  def sign_up
  # Just an example, 
    expect(username.size).to be(1)
    fill_in('Username', with: 'test_username')
    fill_in('Email', with: 'pftest@email.com')
  end

end
```

```
# spec_helper.rb
require 'capybara'
require 'capybara/rspec'
require 'rspec/expectations'
require 'byebug'
require 'selenium-webdriver'
require 'site_prism'

require 'pathname'

Capybara.default_driver = :selenium_chrome
Capybara.app_host = 'https://www.github.com'

Dir["support/**/*.rb"].each { |f| require f }
```

**Comment by luke-hill** [comment]
So couple of things to note.

Firstly, this isn't advised. You ideally should do your assertions inside your testing framework, not the Page Object Model.

Secondly, in order to do this, you would need to include whatever testing assertions you wanted to make inside the page object. So as a base attempt you could do something like `include RSpec::Matchers`

If you wanted to wait until there was 1 username field. I would use either implicit or explicit waits (Both of which are provided in the SitePrism framework).

It's also worth noting your assertion would fail because `element` returns a `Capybara::Node::Element` not an array, so you would probably want to assert something else.

**Comment by serhatbolsu** [comment]
this is very good explanation , thank you @luke-hill , more clear now

**Comment by serhatbolsu** [comment]
@luke-hill Thanks again for suggestions however I have 1 important case:

If I use `include RSpec::Matchers` then capybara/rspec in features files are not working since they are overwritten by Rspec Matchers. 

The reason I would need assersion is that I also want page object to act as a DSL to actions to take in that page. Sometimes you need to validate something  and call the other keyword which is also in page object. Right now I will have duplicate codes in test cases since I have to go back to test case , validate and then call another keyword.

**Comment by luke-hill** [comment]
Can you add a SSCCE and I will re-triage

**Comment by serhatbolsu** [comment]
Here is the expect condition inside the page object: 
```
# page object
class Client < SitePrism::Page
  set_url '/clients'

# element definitions

  def add_client(client_typeval='user')
    add_client_btn.click
    client_form.client_type.select(client_typeval.capitalize)
    client_form.submit_client.click
    expect(page).to have_no_content('Client Type')
  end
```

where an test case you have to write since you can not add expect inside page object: 
```
# Test Suite

feature 'Client Test Suite' do
  scenario 'Add new client as user' do
    @app.client.add_client(:user)
    expect(page).to have_no_content('Client Type')
    @app.client.search_client('prospect client')
    @app.client.client_list[0].official_name.has_content?('User Info')
    expect(@app.client.client_list[0].status.text).to eq('PROSPECT')
  end
```
as it could be like this: 
```
#instead write as 
feature 'Client Test Suite' do
  scenario 'Add new client as user' do
    @app.client.add_client(:user)
    @app.client.search_client('prospect client')
    @app.client.client_list[0].official_name.has_content?('User Info')
    expect(@app.client.client_list[0].status.text).to eq('PROSPECT')
  end

```

**Comment by ineverov** [comment]
@serhatbolsu what will happen if adding client fails? it probably will stay on the same page and will have "Client Type". **I wouldn't recommend doing this**.

If you really want this to be done, you can do it 2 ways
1) Use full matchers instead of shortcuts 
```
RSpec::Expectations::ExpectationTarget.new(page).to RSpec::Matchers::BuiltIn::Has.new('have_no_content', 'Client Type')
```

2) 
```
# page object
class Client < SitePrism::Page
  include RSpec::Matchers
  include RSpec::Expectations::Syntax
  RSpec::Expectations::Syntax.enable_expect

  set_url '/clients'

# element definitions

  def add_client(client_typeval='user')
    add_client_btn.click
    client_form.client_type.select(client_typeval.capitalize)
    client_form.submit_client.click
    expect(page).to have_no_content('Client Type')
  end
```

**Comment by luke-hill** [comment]
This is a conflict between Capybara and RSpec, not directly controlled or monitored by `site_prism`

Some of your code feels as if you're doing 3/4 things in one step, I'd look into using waiters instead of expectations and also remember the TIL (Test Isolation Principle), test one thing at once.

**Comment by serhatbolsu** [comment]
@ineverov  thank you for your suggestion, I will try this approach
@luke-hill yes, I will close with these suggestions
thanks
