### ISSUE TITLE
Add a CHANGELOG.md file

### ISSUE THREAD

**Issue by zedtux** [natritmeyer/site_prism#373]
Because it ease our lives 😃

**Comment by tgaff** [comment]
Hey @zedtux does the HISTORY.md not fill this need for you?  I feel like luke-hill does a lot of work on maintaining it.

https://github.com/natritmeyer/site_prism/blob/master/HISTORY.md

**Comment by zedtux** [comment]
Yeah, looks like it's a change log file ... why don't you name it as `CHANGELOG.md` like everyone does/expect? 😅

**Comment by luke-hill** [comment]
It was called HISTORY when I joined this repo. I can change it if you'd prefer... I guess the consensus is to call it changelog.

**Comment by zedtux** [comment]
As you wish, but have a look around in popular repos, everybody is using Markdown so has a `CHANGELOG.md` file. 😉

**Comment by luke-hill** [comment]
I think you missed the point I was trying to make. I'm not denying that (And I work on many OS repos), just that the one here was called HISTORY so I opted to keep consistency.

Closed in #374

**Comment by zedtux** [comment]
Oh ... I see. Sorry for the misunderstanding. And thank you for the update 👍
