### ISSUE TITLE
Ability to skip load validation

### ISSUE THREAD

**Issue by JanStevens** [natritmeyer/site_prism#382]
Hello,

I would like to optionally skip load validations. For example I'm testing a redirect flow where in some cases the page I try to visit redirects to another page first because the user needs to perform an action.

1. go to `/app`
2. redirect to `/app/accept_gdpr`
3. user accepts and we are back on `/app`

When step 2 is already done we instantly go to `/app`, with site prism 3.1 I get the following error on step 1: `Expected http://127.0.0.1/app/accept_gdpr to match /app but it did not.`

Which is obvious since we navigate to `/app` but get redirected to `/app/accept_gdpr`. So my question is how can I temporarily disable the load validation?

**Comment by luke-hill** [comment]
Good question. Let me have a think / debate on this for a few days.

I have all the info needed. What I would say is that calling `#load` basically only does a couple of things, so you could bypass this by using the wrapper method

**Comment by luke-hill** [comment]
Can I ask whether calling `visit` is enough for this. Or do you still need some of the settings the `#load` method provides.

I'm not against coding this up (And it's not a particularly hard use case), I'm trying to understand if it's something that's worth investing time into.

Alternatively, if you wished to code it yourself I would happily review and merge it and release it in v3.2

**Comment by JanStevens** [comment]
I did try out `visit` and indeed it seems to work fine for the use case. I'm open for adding a new method, not sure what to call it but I guess it should contain the following

```ruby
def load_direct(expansion_or_html = {}, &block)
  if expansion_or_html.is_a?(String)
        @page = Capybara.string(expansion_or_html)
        yield self if block_given?
      else
        expanded_url = url(expansion_or_html)
        raise SitePrism::NoUrlForPageError unless expanded_url

        visit expanded_url
    end
end
```

Or we can also add another option to `load` with `skip_validation: true` and skips the load validations (I think those are in `when_loaded` but not 100% sure)

**Comment by luke-hill** [comment]
In short any new code should always adhere to the basic software tenets.
- Should be backwards compatible (As it's a small change this shouldn't be an issue)
- Have docs/tests for it (Feature / unit would be lovely, but I'd happily accept only unit)

In my eyes, this is a modification of the existing load method, so you should just allow a symbol kwarg.

`def load(with_validations: true)` - This seems to cover the situation. Then you would simply pass this variable through.

Or you could have a config setting `SitePrism.disable_validations` - There's a couple of ways for you.

**Comment by JanStevens** [comment]
Great and what piece of code does actually check the load validations?

**Comment by luke-hill** [comment]
`when_loaded(&block)` begins the checks, but they will do a variety of things "inside" there.

Blocking the `when_loaded` call will stop all load_validations from being executed. so covering that with a guard clause or conditional should suffice
