### ISSUE TITLE
individual Section in sections do not exec block

### ISSUE THREAD

**Issue by tgaff** [natritmeyer/site_prism#395]
# Issue to raise for SitePrism framework
```rb
  section :my_section, MySection, 'div.locator'

  @page.my_section do |section|
    section.something # executes
  end

 sections :my_sections, MySection, 'div.locator'  #

  @page.my_sections.first do |section|
    section.something # does not execute block
  end
```

While the second behavior is not explicitly documented, one would it expect it to work since `:sections` is in many ways an Array-like of `:section`.  Not sure whether this should be considered a bug or feature-request, but failing to execute the block could lead to incorrectly-passing tests.

## Environment
- OSX
- SitePrism itself at recent master 4c568ddf7029273fcb02c3230b21a82b11d54c44
- SitePrism's own cucumber scenarios
- firefox default

## Expected Behavior
We can exec inside a section similar to Capybara `within` functionality on an individual section.  But on an array of sections generated by `:sections` this does not work.  
I expected that my block would be executed when passed as `@page.my_sections {|s| raise 'ermagerd'}`

## Actual Behavior
Code in the block is not exec'd

## Steps to reproduce
1.  clone https://github.com/tgaff/site_prism/tree/tg/sections_dont_exec_blocks
1. `cucumber -r features`
1. observe test failure

## cucumber scenario

In the below I verify that on the Section features we do execute the contents of the block.
However when it comes to the Sections features, the same functionality fails - the block is not executed.  Specifically the tests fail with:

```sh
    Then I can execute in the context of a section using a block # features/step_definitions/sections_steps.rb:22

      expected: 2
           got: 0

      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/sections_steps.rb:39:in `"I can execute in the context of a section using a block"'
      features/sections.feature:21:in `Then I can execute in the context of a section using a block'

Failing Scenarios:
cucumber features/sections.feature:19 # Scenario: access elements in the section by passing a block

91 scenarios (1 failed, 90 passed)
229 steps (1 failed, 228 passed)
0m23.693s
```

Patch that reproduces this behavior

```
diff --git a/features/sections.feature b/features/sections.feature
index 1705336..4f9aee8 100644
--- a/features/sections.feature
+++ b/features/sections.feature
@@ -15,3 +15,7 @@ Feature: Interaction with groups of elements
   Scenario: anonymous sections collection
     When I navigate to the nested section page
     Then I can see a collection of anonymous sections
+
+  Scenario: access elements in the section by passing a block
+    When I navigate to the nested section page
+    Then I can execute in the context of a section using a block
diff --git a/features/step_definitions/section_steps.rb b/features/step_definitions/section_steps.rb
index a56cd57..45e5bb0 100644
--- a/features/step_definitions/section_steps.rb
+++ b/features/step_definitions/section_steps.rb
@@ -12,13 +12,19 @@ Then('I can see a section in a section') do
 end

 Then('I can access elements within the section using a block') do
+  block_inner_executions = 0
+
   expect(@test_site.home).to have_people

   @test_site.home.people do |section|
+    block_inner_executions += 1
+
     expect(section.headline.text).to eq('People')

     expect(section).to have_individuals(count: 4)
   end
+
+  expect(block_inner_executions).to eq 1
 end

 Then('I cannot access elements that are not in the section using a block') do
diff --git a/features/step_definitions/sections_steps.rb b/features/step_definitions/sections_steps.rb
index f57cbe7..4e1f0c9 100644
--- a/features/step_definitions/sections_steps.rb
+++ b/features/step_definitions/sections_steps.rb
@@ -17,3 +17,24 @@ Then('I can see a collection of anonymous sections') do

   expect(anonymous_sections.size).to eq(2)
 end
+
+
+Then('I can execute in the context of a section using a block') do
+  block_inner_executions = 0
+
+  expect(@test_site.nested_sections).to have_search_results(count: 4)
+
+  @test_site.nested_sections.search_results.first do |sec|
+    block_inner_executions += 1
+    expect(sec).to be_an_instance_of(SitePrism::Section)
+    expect(sec).to have_text('Result 0')
+  end
+
+  @test_site.nested_sections.search_results.last do |sec|
+    block_inner_executions += 1
+    expect(sec).to be_an_instance_of(SitePrism::Section)
+    expect(sec).to have_text('Result 3')
+  end
+
+  expect(block_inner_executions).to eq 2
+end
```

**Comment by luke-hill** [comment]
Definitely a bug. If you've got bandwidth feel free to dig in. It's likely that the area in which it will need looking is around here: https://github.com/natritmeyer/site_prism/blob/master/lib/site_prism/dsl.rb#L116

This map which creates the constructor (per se), is not passing the defined runtime block (Furthermore we make the check for element block - as intended).

To me this "may" be a 1line fix? But I've not got time to investigate as I'm deep into this recursion stuff.

**Comment by tgaff** [comment]
I'll try to figure it out.  Might not be till next week though.  Wanted to make sure we intend to support this as a feature first.  Sorry I've been so busy!

**Comment by luke-hill** [comment]
No probs. I'm likely to be making a new subgem for all the work I've been getting into with the recursion work, as it's seen me dive into a whole new inheritance / class structure. So just do what you can

**Comment by tgaff** [comment]
Hmm, I'd be interested to know more about that structure and whether it might be applicable to this bug.  

From what I'm seeing here now I have a suspicion that this isn't a trivial fix.  
I'm either going to need to add a Section#within method and use that instead of exec'ing the block in `initialize` or implement an iterable replacement for the array of sections we use, e.g. a SectionCollection class.

**Comment by luke-hill** [comment]
You've actually exposed a larger issue (Which I'm not sure is explicitly tested). Which is the raise_if_block check doesn't seem to be working!

**Comment by luke-hill** [comment]
See #397 for a similar issue. Both of these are separate bugs though. I'm making a deprecator class to triage these and we can then start firing warnings / fixing as we deem fit.

**Comment by tgaff** [comment]
Yeah I noticed.  I'm wondering why we'd want to prevent a block there though.  We support both run-time and define-time blocks on section, so I'm not sure if this code just snuck through or if there was real intent here to prevent blocks.

**Comment by luke-hill** [comment]
those blocks are never parsed and they're ignored. For now I'm going to put in a soft-deprecation to ban that code in 2 major versions time. Next version will warn users to remove them.

A lot of this is just edge cases which are likely to have been missed.

**Comment by luke-hill** [comment]
@tgaff are you working on this?

**Comment by tgaff** [comment]
I need to be.  I haven't been.  :-/  sorry.

So I had two thoughts on how to tackle this AND keep the current expected functionality.

1) Build a SectionCollections class that implements all the usual array methods `:[], :first, :last, :map` but passes around the blocks as needed.

OR 

2) deprecate the current style of passing a block directly to a section and add a `.within` (or similar) method on sections that does take a block.  That way when you have `my_sections.first.within {|s| }` the block can be executed in the right context.

I think I prefer #2 since it's more similar to Capybara (which many users already have experience with) and is almost certainly easier to implement/maintain.  Of course...that means another round of deprecation and we have to maintain the current "broken" functionality for some time.  I suppose we could do both and just remove the SectionCollections after the deprecation date.

**Comment by luke-hill** [comment]
Why don't you just pass the block into the existing method as it's done for the others. I had a quick play and it should just work with a 1/2liner change.

But go with whatever you feel is best. I'm still tidying things up and doing the deprecations soon. So I've got enough with getting the 2 gems co-dependent.

**Comment by luke-hill** [comment]
Also just as an FYI, I'm not sure how much more into the 3.x series we'll go. As there's no chunky features people are requesting / proposing and not a lot of bugs I'm finding. So I think a 4.x series is definitely feasible sometime late 2019 or early 2020. At least that's my plans.

**Comment by luke-hill** [comment]
Any updates on this @tgaff ?

Just reviewing the status' on this (the old repo)

**Comment by luke-hill** [comment]
Kamino closed and cloned this issue to [site-prism/site_prism](https://github.com/site-prism/site_prism/issues/21)
