### ISSUE TITLE
all_there? should be recursive

### ISSUE THREAD

**Issue by tmertens** [natritmeyer/site_prism#49]
Presently all_there? only checks if the direct child elements of a page or section are present on the page, but does not ensure that all required descendant elements of those child elements are also present.

**Comment by luke-hill** [comment]
Hi @tmertens You'll notice I've been bumping a few tickets recently and getting peoples input.

Can this and #48 be looked at and closed. I believe there is a PR tidying up `all_there?` slightly which will be merged soon.

**Comment by luke-hill** [comment]
Will see if the demand for this is high enough. Have refactored this area recently though
