### ISSUE TITLE
Window Maximize 

### ISSUE THREAD

**Issue by ramyav** [natritmeyer/site_prism#58]
Hi Nat, I've been using site prism for my client and it looks really good. The one thing I'm struggling to do is find a DSL to maximize the browser window. Currently am using 

 Capybara.current_session_driver.browser.manage.window.maximize

to maximize the window and it kind of feels a bit odd to use the Capybara one as site_prism as i currently understand provides a wrapper around capybara.

Apologies if this is not the right place for this  or there is already one available to do this functionality

**Comment by natritmeyer** [comment]
Thanks @abotalov
