### ISSUE TITLE
dynamic sections with dynamic filter #text returns text for section without filter

### ISSUE THREAD

**Issue by tgaff** [natritmeyer/site_prism#72]
Bug in sections(text: 'something').first.text -> returns the text without the filter.  Capybara doesn't do this.

I need to track this down still, but it's looking like:

``` ruby
sections :some_section, 'tbody.users tr' do 
  element :some_link, 'a'
end

........


some_sections(text: 'User1').last.text.match /User3/ # true?
# versus
page.all('tbody.users tr', text: 'User1').last.text.match /User3/ # false
```

Logging this to investigate and reproduce.    (self#todo)

**Comment by luke-hill** [comment]
Hi @tgaff I know we spoke yesterday about a previous PR you had raised. But you've raised an Issue here with Self TODO.

The repo is going to start seeing a lot more new activity, and if you're willing to look into this and the other Travis Item I can promise you they will be looked at in a timely manner (Definitely in the next 2-4 weeks)

Let me know how you feel. If you think this is something which is no longer an issue then just close it up

Cheers,

Luke

**Comment by tgaff** [comment]
I'll try to figure out where I saw this occurring and reproduce it.

**Comment by tgaff** [comment]
I believe I've reproduced it.

In the below there was only one tr with 'Blood' on it.  (Err... no pun intended.)

```ruby
[38] pry(#<RSpec::ExampleGroups::...>)> p.teaching_courses(text: 'Blood').last.text     # demonstrate that site_prism is getting text for all rows in this table, despite the text filter
=> "Edit registration Logout Course Information for g1@g.com My Courses Teaching Course Title Blood Spatter Analysis Show Edit Edit my calendar Destroy Basket Weaving Show Edit Edit my calendar Destroy Raising Children Show Edit Edit my calendar Destroy"
[39] pry(#<RSpec::ExampleGroups::...>)> page.find_all('table tbody tr', text: 'Blood').last.text      # demonstrate that Capybara shows only the text for this row
=> "Blood Spatter Analysis Show Edit Edit my calendar Destroy"
[41] pry(#<RSpec::ExampleGroups::...>)> p.teaching_courses(text: 'Blood')                  # show that the selected Capybara::Node::Element appears to be correct
=> [#<CourseListingSection:0x007fc570b636a8
  @parent=#<CoursesIndexPage:0x007fc56a6efed8>,
  @root_element=
   #<Capybara::Node::Element tag="tr" path="/html/body/div/div[2]/div[2]/div[1]/div[2]/table/tbody/tr[1]">>]

```

Reproduced with: 
    capybara (2.5.0)
    site_prism (2.7)
   rspec-rails (~> 3.0)

**Comment by tgaff** [comment]
However,

By site_prism 2.9 I think this is fixed:

```ruby

[11] pry(#<RSpec::ExampleGroups::...>)> page.find_all('table tbody tr', text: 'Basket').last.text   # results are as expected from Capybara
=> "Basket Weaving Show Edit Edit my calendar Destroy"
[12] pry(#<RSpec::ExampleGroups::...>)> p.teaching_courses(text: 'Basket').last.text    # site_prism now returns correct results too!
=> "Basket Weaving Show Edit Edit my calendar Destroy"
[13] pry(#<RSpec::ExampleGroups::...>)> p.teaching_courses(text: 'Basket').last
=> #<CourseListingSection:0x007ff553b032e0
 @parent=#<CoursesIndexPage:0x007ff553fc1750 @loaded=false>,
 @root_element=
  #<Capybara::Node::Element tag="tr" path="/html/body/div/div[2]/div[2]/div[1]/div[2]/table/tbody/tr[2]">>

```

    capybara (2.18.0)
    site_prism (2.9)
    rspec (3.3.0)

I think this can be closed, unless you see a flaw in my approach.

**Comment by luke-hill** [comment]
Nah thats fine. I noticed that because we mainly rely on the Capybara framework and in terms of commits 2.5 - 2.18 represents over 300. It's safe to say something there got better.
