### ISSUE TITLE
Problem with Inheritance section and page

### ISSUE THREAD

**Issue by jtlimo** [natritmeyer/site_prism#73]
Hi natritmeyer. Thanks for your amazing job with site_prism.
I'm newbie with site_prism, ruby...etc
I read the doc of site_prism, and I implement site_prism in my tests , but when I trying to use pages with section occurs an error.

An example: I execute this command bundle exec cucumber features/events.feature
When I run this command the Iterm shows that error: `uninitialized constant Admin::Menu (NameError)`

I have the `class Admin < SitePrism::Page`

And I have the `class Menu < SitePrism::Section`

The class Admin contains these code:

``` ruby
section :menu, Menu, "menu-wrapper"
section :section_crudAllRules, CRUDRules, :class, "row rules" 
```

I really appreciate your job.

Thanks for help.

**Comment by bryzhevska** [comment]
@tmertens  thank you, it helps.
