### ISSUE TITLE
wait for staleness

### ISSUE THREAD

**Issue by alvy54** [natritmeyer/site_prism#74]
Hi natritmeyer,
I have an element that I wait for to exist in the DOM but then I want to wait for it to be removed afterwards.  So far I call wait_for_element_name but then I need something like wait_until_element_name_stale.  Please advise.

Thanks,
Alvin

**Comment by PikeIt** [comment]
@alvy54 I faced the same issue

@natritmeyer Please review and merge Pull request https://github.com/natritmeyer/site_prism/pull/139/

**Comment by luke-hill** [comment]
Closing in favour of PR
