### ISSUE TITLE
Better API for url handling

### ISSUE THREAD

**Issue by abotalov** [natritmeyer/site_prism#81]
Current SitePrism API for handling urls has a number of design issues:
1. It's not possible to associate the same page object with several urls/url templates. It's a real situation as it's possible to point different routes to the same view
2. `Addressable` provides a useful feature to check if url matches template. So it should be possible to get `Addressable::Template` from page object to match it easily with url using addressable's `#match` method. Note that this feature of `Template` makes `set_url_matcher` functionality unnecessary as it's possible to define url template that can be used both for loading and matching url of the page.
3. It's good that Capybara allows to set `app_host` and it's not necessary to specify hostname when invoking `visit` after it. Therefore page object may contain relative url as its url: `set_url '/path'`. Also it would be good to have a way to check if `current_url` (i.e. absolute url matches url template from page object).

To handle all this I propose the following API (it seems to be backwards compatible from the first glance with existing API):

``` ruby
SitePrism::Page#url(key, expansion = {})  # returns expanded url [String]
SitePrism::Page#absolute_url(key, expansion = {}) # returns absolute url (it's combined using app_host and #url) [String]
SitePrism::Page::url_template(key)        # returns url template [Addressable::Template]
SitePrism::Page::url_templates            # returns array of url templates [Array<Addressable::Template>]
SitePrism::Page#load(key, expansion = {}) # loads expanded url
```

In the above definitions `key` is a key of url. It's an optional parameter if page object is associated with only one url. `#load`/`#url` would actually take `*args` as it needs to handle this.

Then this API can be used as:

``` ruby
class SearchPage < SitePrism::Page
  set_url '/search{?query*}'
end

# Open page number 50 in paginator
m = SearchPage.url_template.match(current_path) # current_path is "/search?q=testing&page=1"
m['query']['page'] = 50
SearchPage.new.load(m)  # loads "/search?q=testing&page=50"

# Check if correct url was opened after clicking Next button in paginator
m = SearchPage.url_template.match(current_path)
click_button 'Next'
m['query']['page'] = 2
expect(SearchPage.new.url(m)).to eq(current_path)

# Check if after clicking some button signup page matching particular url template is opened (expansion parameters aren't important):
class SignupPage
  set_url :key1, '/sign_up{?email}'
  set_url :key2, '/users/new'
end
SignupPage.new.load(:key1, email: 'test@example.com')
expect(SignupPage.url_template(:key1)).to match(current_path) # I think it should work as RSpec doesn't seem to care about class - https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/match.rb#L24

# Check if after clicking some button any signup page opened (don't care about matching particular url template)
expect(SignupPage.url_templates).to include(an_object_matching(current_path))

# Load the same page at different hostnames
class AnotherPage < SitePrism::Page
  set_url '/path'
end
Capybara.app_host = 'https://www.example.com'
AnotherPage.new.load # opens page via https
expect(AnotherPage.absolute_url).to match(current_url) # checks full url (and also that url scheme is https)
Capybara.app_host = 'http://www.example.com'
AnotherPage.new.load # opens page via http
expect(AnotherPage.absolute_url).to match(current_url) # checks full url (and also that url scheme is http)
```

Please approve.

**Comment by luke-hill** [comment]
Hi @abotalov There seems quite a lot of moving parts in here. And as you've documented it all quite well I have a couple of suggestions.

Possibly look to partition your work into 2, and raise 2 PR's for it (Obviously if you're still keen / interested)
Get them raised and onto the PR system and we'll look to get them in as and when. It's likely they'd probably hit the gem in some form in possibly 2.11 (Providing they aren't breaking changes, which they don't seem to be).

Does that all sound good? I'm aware this is a few years old. But I've just started looking into all these existing issues and triaging / prioritising where appropriate.

**Comment by luke-hill** [comment]
If you want to raise some PR's for this feel free. Will close this now though
