### ISSUE TITLE
Provide ability to set locator of root element in section class

### ISSUE THREAD

**Issue by abotalov** [natritmeyer/site_prism#85]
Consider the following example (modified from SitePrism README):

``` ruby
class MenuSection < SitePrism::Section
end
class Home < SitePrism::Page
  section :menu, '#gbx3', MenuSection
end
class SearchResults < SitePrism::Page
  section :menu, '#gbx3', MenuSection
end
```

So `#gbx3` should currently be specified in several places which isn't DRY.

IMO in many situations a section (i.e. menu/search bar/authentication form) is likely to have the same locator of root element that is specified in partial.

Therefore, I propose to add ability to do the following:

``` ruby
class Menu < SitePrism::Section
  set_root_locator '#menu'
end
class Home < SitePrism::Page
  section :menu, Menu
end
class SearchResults < SitePrism::Page
  section :menu, Menu
end
```

For example HTMLElements seem to also provide such ability - https://github.com/yandex-qatools/htmlelements#create-blocks-of-elements (using `@Block(@FindBy(xpath = "//form"))` annotation

If it will be approved I can do PR.

**Comment by Tensho** [comment]
+1

**Comment by tgaff** [comment]
:+1: I also wanted something like this over a year ago.

**Comment by tgaff** [comment]
btw, @abotalov I think your code example for section should say:
`  section :menu, MenuSection, "#gbx3"`

**Comment by luke-hill** [comment]
Hi @abotalov This dovetails with some other items around similar areas that people have mentioned. I think you've hit something though that feels a bit safer than the other topics mentioned.

Was this more of a brainstorm / idea, or something that you had mocked up. What are your thoughts with this going forwards? To land a PR or to keep this active for more discussion. Or just to close?

**Comment by tgaff** [comment]
I agree with what @luke-hill says above.  This PR and #161 are both affecting similar code and how `section` is to be called.  

Starting with the original:
`section :menu, MenuSection, "#gbx3"`

PR #161  proposes to find the section's class automatically (via convention) resulting in:
`section :menu, "#gbx3"  `

This PR #85 proposes 
`section :menu, Menu`


Combining the two would yield the clean and wonderfully simple:
`section :menu`

Which to me at least seems quite nice and I think would cover many section use cases.  

(1)
We might want to think about whether these changes should come at the same time or not.  I think for the simplicity of anyone using this, doing them simultaneously will allow us to be as clear as possible and reduce the amount of potentially confusing cross-messaging if they were to strike a couple of weeks apart.  

(2)
Also, if this simplified method becomes standard I have a suspicion that forgetting what the *full* argument order is will become somewhat common.  I might end up mistakenly using `section :menu, '#gbx4, OtherMenuSection`.  (It actually looks like that occurred in the text of this PR at one point already.  
We might be able to use named or hash arguments to help out with this for the odd times when someone needs to add the extra info.  `section :menu, class: SomeOtherClass, locator: '#gbx4'`  (Please don't interpret this as trying-to-throw-the-brakes-on, far from it - just points to think about.)

**Comment by luke-hill** [comment]
Ping @abotalov - Not sure if you're still getting updates on this or not

**Comment by abotalov** [comment]
@luke-hill I get updates, but I don't use SitePrism currently.

**Comment by luke-hill** [comment]
Rightio. Are you wanting to work on this PR then or is it of no use to you now? @abotalov

**Comment by ineverov** [comment]
@luke-hill @tgaff I can work on this, but I have a couple questions to discuss.
About  #161: 
1) How do you want to perform `camelcase.constantize` for section name to convert to class? Adding extra dependency is not better than copy-pasting part of [activesupport](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-constantize) for example
2) Do you want to force class name to ends with `Section`, i.e. `:menu => MenuSection`, `:menu_section => MenuSection`
3) Do we want support for namespaced classes? i.e. `MyModule::MenuSection`. If yes, how do you see it?

About [`#85`](https://github.com/natritmeyer/site_prism/issues/85):
4) Do you want parameters to be overridden/merged/concatenated? i.e.
```ruby
class MenuSection << SitePrism::Section
   set_default_search_arguments '.some_class', text: 'Menu'
end

class MyPage << SitePrism::Page
   section :menu, '.other_class', text: 'New Menu'
end
```

@tgaff (1) I think it's better to do it at the same time. (2) This should not be an issue, IMO.

**Comment by luke-hill** [comment]
2) I do not think we should infer any name. Remember this is just providing the default selector unless otherwise specified on a specific class.

3) The namespacing should have no effect. On a class basis you are providing the default selector.

No opinion on #1. Do it however you see fit. I'd rather have something inter-library than introducing an extra dependency. However again, I think you're combining multiple pieces of work. Remember this piece of work is JUST a default locator.

**Comment by luke-hill** [comment]
Closing in favour of PR
