### ISSUE TITLE
Timeouts don't fire if you've stopped time

### ISSUE THREAD

**Issue by yozlet** [natritmeyer/site_prism#88]
This one took ages to debug:

```ruby
describe "test the button link! (This doesn't work yet)" do
  @page.button.click_link # Link is broken because I haven't implemented it yet
  expect(@page2).to be_displayed # Spec hangs here forever
end
```

What I want to happen: RSpec fails the test because the button link doesn't work.
What actually happens: RSpec hangs at line 3 forever.

If you've used Timecop to freeze time at a specific point, and if the link is broken, SitePrism will just wait for page2 to appear forever, irrespective of any timeouts you've set. This is because Timecop has stopped time and SitePrism's timeouts are susceptible to that. (Perhaps there's a better, non-timecop-susceptible way of doing timeouts?)

**Comment by natritmeyer** [comment]
@jmileham is right, this isn't something that siteprism should have to deal with.
