### ISSUE TITLE
Site Prism Doesn't have logging feature

### ISSUE THREAD

**Issue by kedar2014** [natritmeyer/site_prism#94]
With Logging feature , we might have to log the actions and data used during these actions to be logged at a place. This helps in debugging , Analyse the failures. These features are implemented if we write our own page object gem.

I think this can be a good addition. As currently we are using Builder Pattern(to generate our test data). This require Logging of this runtime data for future analysis

**Comment by natritmeyer** [comment]
There are plenty of gems out there that will do logging for you.
