### ISSUE TITLE
elements is an RSpec matcher class, rather than a collection

### ISSUE THREAD

**Issue by swolfekabaminc** [natritmeyer/site_prism#95]
using the 'elements' method to set a collection of elements on a page. Rather than getting an array of elements, I'm getting an RSpec matcher:

    class ManagePages < BasePage
        elements :edit_links, 'a.edit'
    end

    ...
    @manage_page = ManagePage.new
    @manage_page.edit_links
    #<RSpec::Matchers::BuiltIn::All:0x00000104253e88 @matcher="a.edit", @failed_objects={}>

that last should give me an array, not an RSpec matcher ... ?

**Comment by natritmeyer** [comment]
@swolfekabaminc if you include library A into library B and both have the same method name, you're going to get clashes.
